### ISSUE TITLE
Master Node not added as target in LoadBalancer

### ISSUE THREAD

**Issue by kasokz** [hetznercloud/hcloud-cloud-controller-manager#101]
Hi,
I setup a Kubernetes Cluster using kubeadm and want to use the Load Balancer feature of the HCloud CCM. It actually works great, but I have one uncertainty going on. My master node is not automatically registered as target on the LoadBalancer instance when I deploy the Ingress controller for the first time. I only noticed this behaviour when I recently setup a staging Kubernetes environment and started out with one node only first. No target was added at all and I needed to manually add the master node as target, so Ingress routing could work at all.

# Process/Deployment
- Created private network and subnet in 10.92.0.0/16 range
- Deployed Kubernetes v1.17.3 with Flannel as CNI and with 
```
cat <<EOF >/etc/systemd/system/kubelet.service.d/20-hetzner-cloud.conf
[Service]
Environment="KUBELET_EXTRA_ARGS=--cloud-provider=external"
EOF
```

- Installed the cloud controller manager with Network support.
- Installed Nginx ingress controller using following Helm command and values:
`$ helm install ingress ingress-nginx/ingress-nginx --namespace ingress --values ./ingress-controller/values.yaml`
```
controller:
  service:
    annotations:
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/use-private-ip: "true"
defaultBackend:
  enabled: true
```

# Problem
The Load Balancer is created and can be seen in the Hetzner Cloud Console, but no Target is added.
The TCP Services for ports 80 and 443 are added as expected.
The Ingress Service gets the Load Balancer Address as External IP as expected.
When joining additional Nodes they are automatically added as targets.

Is this expected? I purposefully want to load the Master node with Pods and have thus remove the taints using `kubectl taint nodes --all node-role.kubernetes.io/master-`. HCloud CCM either ignores this or has some other labels on the Master Nodes. Is there a configuration that I'm missing or am I just making a mistake during deployment? I'm pretty sure this is not the case, since, as mentioned, joined worker nodes are registered automatically.

**Comment by LKaemmerling** [comment]
The CCM doesn’t specify the list of nodes, this comes directly from k8s. Within the k8s world „master“ nodes by default aren’t scheduleable. You need to remove the master label and taint. We had an issue for this within the repo, I will search it for you.

**Comment by LKaemmerling** [comment]
Or better, I send you the link to our e2e tests, they run onto one node k8s clusters
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/3c67bb75b7956006e94f68804f31b099ae989aea/e2etests/templates/cloudinit.txt.tpl#L39

**Comment by kasokz** [comment]
Thank you very much, this was really the problem. It is not enough to remove the taint, the label also needs to be removed.
Should have considered this, since taints are specific to the kube-scheduler and not supposed to be used to search and select nodes, I guess?

**Comment by mysticaltech** [comment]
@LKaemmerling Instead of looking for the word "master" can you instead look for "NoSchedule"? That would solve the same issue we have over at kube-hetzner/terraform-hcloud-kube-hetzner! 

Please see the mention above. Because there is not much more we can do than ask you to change that behavior! It would really be great! 🙏

**Comment by mysticaltech** [comment]
Ah, @LKaemmerling, I just saw your comment above about `kubectl label nodes --all node-role.kubernetes.io/master-`. We will try that and report back!
