### ISSUE TITLE
Kontena Pharos support

### ISSUE THREAD

**Issue by hadifarnoud** [hetznercloud/hcloud-cloud-controller-manager#11]
Kontena Pharos does not support Hetzner Cloud. there is no addon for it. I asked their support and they said this controller manager can be used for that.

I have no idea how to make Pharos addon. I'm too novice for that. Would you guys please add support for [Kontena Pharos](https://github.com/kontena)?

**Comment by invidian** [comment]
I guess that's more an issue to Kontena rather than Hetzner. @hadifarnoud I guess you can use https://github.com/kontena/kontena-plugin-aws as example for implementing Hcloud plugin.

**Comment by invidian** [comment]
As Kontenta is out of business, can we close this issue?
