### ISSUE TITLE
Hetzner Network Route is overwritten by the same gateway

### ISSUE THREAD

**Issue by StarpTech** [hetznercloud/hcloud-cloud-controller-manager#110]
I'm running a rancher cluster on hetzner cloud. After removing/adding some servers, I got the error

```
Failed to delete controlplane node [10.0.0.3] from cluster: Get "https://10.0.0.7:6443/api/v1/nodes": net/http: TLS handshake timeout
Rancher: v2.5.1
```

After some investigation, I saw (Cloud Console UI) two routes with different targets but the same gateway `10.0.0.6`. No route for `10.0.0.7`. Before the operation, every server had a route.

It looks like there is a big issue in the route configuration.

**Comment by LKaemmerling** [comment]
Can you give us the logs from the cloud-controller in the kube-system namespace?

**Comment by StarpTech** [comment]
Unfortunately, I had to remove it. Could it be related to https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/107? I configured `--configure-cloud-routes=false`.

**Comment by LKaemmerling** [comment]
I think all the issues you have are based on a wrong network configuration. If you want to use our Hetzner Cloud Networks, you can't disable `--configure-cloud-routes=false` and should use this Cloud Controller Manager deployment file: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/deploy/ccm-networks.yaml

If you don't want to use our Hetzner Cloud Networks you need to use this deployment file: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/deploy/ccm.yaml
