### ISSUE TITLE
Clarification: cluster subnet vs. pod subnet

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/hcloud-cloud-controller-manager#112]
Hey,

since I just stumbled over it, I have a question regarding the clarification of subnet definitions: The README of this repository sets up Kubernetes using a certain subnets for pods. According to https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md, ehe parameter `--cluster-cidr` should match the pod subnet. And then there is another subnet, the nativeRoutingCIDR from cilium.

I find the name `--cluster-cidr` somehow confusing, my first understanding would be "subnet of the whole cluster" (including node, service and pod subnet). But the file in docs tells: pod subnet == cluster subnet. What's with the cilium subnet? Is it also pod subnet?

Best regards
Matthias

**Comment by ByteAlex** [comment]
I've been in discussion with Cilium for the past few days. As far as I figured the two subnets which are important in the cilium configmap are:
  cluster-pool-ipv4-cidr: "10.224.0.0/16" # Your pod-cidr here
  native-routing-cidr: "10.0.0.0/8" # Your networks routable ip cidr here

The native routing cidr defines which ips will *not* be masqueraded.

Yet there's still an issue with how the hetzner CCM is creating the rules in the cloud-console.
Please let me know if you encounter the same issue and if yes, please also share your solution.

**Comment by MatthiasLohr** [comment]
But which of these cilium settings should have the same value as HCCM `--cluster-cidr`? I suspect `cluster-pool-ipv4-cidr`, but I find the naming unintuive and leaving space for chosing the wrong value.

**Comment by ByteAlex** [comment]
As far as I understood the `cluster-pool-ipv4-cidr should` be equal to `--cluster-cidr`.
Yes the documentation is a bit outdated. I'll open a PR on that as soon as I get it working..

**Comment by LKaemmerling** [comment]
Hey @MatthiasLohr,

the flags are provided by k8s. You can find a list of all the flags here: https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/ We are not able to change the flags. 

For cilium:
You don't need to specify any IP range within the config. Cilium get's the whole configuration from the k8s API. Have a look at our cilium config for our tests:
https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/e2etests/templates/cilium.yml#L16
