### ISSUE TITLE
Flag --cloud-provider=external to the kubelet

### ISSUE THREAD

**Issue by unthoiz** [hetznercloud/hcloud-cloud-controller-manager#119]
I have recreated the cluster with a single master with this flag following the steps below (See Step 1. of our  [README.md](https://github.com/hetznercloud/hcloud-cloud-controller-manager)).

When I adding the following worker node I see with a kubectl describe node that it does not create the labels and annotations that I do have in the master node, with systemctl status kubelet in the worker node I observe that it is not using the --cloud-provider flag = external, isn't this supposed to only be done when initializing the cluster on the master node?

I have done the test of this same node worker, reset it and manually add the flag as in the master node before adding it, and it works, but I don't know if something is wrong in my cluster creation and that is why it does not propagate the flags to the rest of the workers.

**Comment by LKaemmerling** [comment]
You should add this flag to all nodes you add to your cluster, otherwise, k8s doesn't know about it on "bootup" time.  Adding it "on runtime" (like when a connection to master node was made) is not possible from k8s side.
