### ISSUE TITLE
Question about HTTP/3 support for hetzner cloud

### ISSUE THREAD

**Issue by schamane** [hetznercloud/hcloud-cloud-controller-manager#123]
Hi,

is there any ETA, roadmap, plans to support HTTP/3 as soon as it comes out, especially with loadbalancers?

Thanks

**Comment by LKaemmerling** [comment]
We plan to look into this when HTTP/3 is officially "released".  Therefore we can not guarantee a date or something like that. We have it on our board :) As this issue isn't directly related to the Cloud Controller Manager i will close it. Thank you!
