### ISSUE TITLE
Have you stopped maintaining this?

### ISSUE THREAD

**Issue by acim** [hetznercloud/hcloud-cloud-controller-manager#13]
I have tried applying this to 1.13.3, Docker 18.06, Ubuntu 16.04, but node taint node.cloudprovider.kubernetes.io/uninitialized doesn't go away. Even pod hcloud-cloud-controller-manager didn't start because it didn't tolerate node.kubernetes.io/not-ready:NoSchedule, I fixed this but still your controller doesn't work. It's a pitty that this is not maintained :(

**Comment by LKaemmerling** [comment]
We don't have stopped maintaining this. It is on our list and we will update it as fast as possible.

**Comment by acim** [comment]
Great, thank you :+1: I am looking forward for the new release.
