### ISSUE TITLE
vSwitch causes route creation to fail

### ISSUE THREAD

**Issue by malikkirchner** [hetznercloud/hcloud-cloud-controller-manager#133]
Using a vSwitch to connect a dedicated server lets route creation fail.
`  Warning  FailedToCreateRoute      2m36s (x8272 over 23h)  route_controller  (combined from similar events): Could not create route e1ced4d4-b410-4b86-9138-72c1ede017b6 10.217.4.0/24 for node starfleet-janeway after 166.14063ms: hcloud/CreateRoute: hcops/AllServersCache.ByName: hcops/AllServersCache.getCache: not found`

I am running hcloud-cloud-controller-manager w/network v1.8.1. Cilium v1.8.2 is the CNI plugin, k8s 1.19.4. It would be great to just have a special label for the nodes, that should be ignored my the controller manager. Actually a couple of days ago it was still possible to create a route to the vSwitch in the web UI and with hcloud. Something changed on your end?

Hetzner network: 10.0.0.0/24
vSwitch : 10.0.1.0/24
CNI CIDR:  10.217.0.0/16
Dedicated server: 10.0.1.2
Route: gateway 10.0.1.2 destination 10.217.4.0/24

**Comment by LKaemmerling** [comment]
Using a dedicated server as gateway within a route is not possible.  We allowed this a few days ago by error. Technically it was never possible (the route never worked).

**Comment by malikkirchner** [comment]
Please don't close the issue, because not allowing it results in taints for the node. 

* node.kubernetes.io/unreachable:NoExecute
* node.kubernetes.io/network-unavailable:NoSchedule
* node.kubernetes.io/unreachable:NoSchedule

The cloud controller manager must ignore the node, so that I can manually create the routes.

**Comment by LKaemmerling** [comment]
@malikkirchner as I said, creating those routes is not supported. Currently the CCM does not support clusters with dedicated servers: #113

**Comment by malikkirchner** [comment]
> @malikkirchner as I said, creating those routes is not supported. Currently the CCM does not support clusters with dedicated servers: #113

That means I need to uninstall CCM for now and wait for #113. That is disappointing, because our hybrid cluster just worked until this change.
