### ISSUE TITLE
choosing features 

### ISSUE THREAD

**Issue by ghorofamike** [hetznercloud/hcloud-cloud-controller-manager#140]
Is it possible to enable the features that this manager provides?  i see the following listed: 

- **instances interface**: adds the server type to the `beta.kubernetes.io/instance-type` label, sets the external ipv4 and ipv6 addresses and deletes nodes from Kubernetes that were deleted from the Hetzner Cloud.
- **zones interface**: makes Kubernetes aware of the failure domain of the server by setting the `failure-domain.beta.kubernetes.io/region` and `failure-domain.beta.kubernetes.io/zone` labels on the node.
- **Private Networks**: allows to use Hetzner Cloud Private Networks for your pods traffic.
- **Load Balancers**: allows to use Hetzner Cloud Load Balancers with Kubernetes Services

Im only interested in the first maybe the second, but definitely not the third or fourth, is there a way to only pick those?

**Comment by eplightning** [comment]
You can disable private networks and load balancers support by changing environment variables:
```
HCLOUD_NETWORK=0 (or simply don't set it)
HCLOUD_LOAD_BALANCERS_ENABLED=false
```

**Comment by ghorofamike** [comment]
great! i see that is uses the ks8  node-ip to identify nodes, is there a possibility that hostnames will be an option in future?

**Comment by LKaemmerling** [comment]
> great! i see that is uses the ks8 node-ip to identify nodes, is there a possibility that hostnames will be an option in future?

We already work with the hostname in the first step and afterward always use the ID that is attached to the server.

**Comment by ghorofamike** [comment]
> > great! i see that is uses the ks8 node-ip to identify nodes, is there a possibility that hostnames will be an option in future?
> 
> @ghorofamike We already work with the hostname in the first step and afterward always use the ID that is attached to the server.

When i tested it it was looking only for the node-ip, so it could not find my servers which are connected via ips from a vpn  for kubernetes networking, tho the servers till have a private network that is not passed to ks8.  thats why i  asked.  as implemented, hostnames are not an option, the node-ip is used to match with the ip's in the API.
