### ISSUE TITLE
Creates/deletes routes constantly in a loop

### ISSUE THREAD

**Issue by vitobotta** [hetznercloud/hcloud-cloud-controller-manager#141]
Hola :)

I opened a support ticket about this but then I realized that it is caused by the cloud controller manager somehow.

I have a cluster with the CCM installed with private network support. I don't have any problems with my workloads etc, but in the Hetzner cloud console I see create/delete events for network routes every second basically. I see equivalent events in the logs of the CCM pod. What is causing this?

A few days ago I have "recycled" the nodes, basically I replaced all of them. I do this every couple of months to have fresh nodes with up to date OS etc. Can this explain this behaviour from the CCM?

Thanks!
Vito

**Comment by vitobotta** [comment]
This is a screenshot from the console for example: https://cln.sh/yYLaCq

And this is a portion of the log:

```
I1230 16:03:14.124875       1 route_controller.go:213] Created route for node epsilon-master-c2 10.244.1.0/24 with hint 32b5ff8a-f938-4b0b-a7d7-b7bfecb0fa84 after 4.037279775s
I1230 16:03:30.164575       1 route_controller.go:193] Creating route for node epsilon-master-c3 10.244.0.0/24 with hint a673ed19-0712-4e3a-b063-bb76a4c51d80, throttled 190ns
I1230 16:03:30.164722       1 route_controller.go:193] Creating route for node epsilon-master-c1 10.244.2.0/24 with hint 6503ceb9-b2d0-4d7e-b74d-6d55061cd818, throttled 271ns
I1230 16:03:30.164778       1 route_controller.go:193] Creating route for node epsilon-master-c2 10.244.1.0/24 with hint 32b5ff8a-f938-4b0b-a7d7-b7bfecb0fa84, throttled 241ns
I1230 16:03:31.669659       1 route_controller.go:213] Created route for node epsilon-master-c1 10.244.2.0/24 with hint 6503ceb9-b2d0-4d7e-b74d-6d55061cd818 after 1.50492421s
I1230 16:03:32.466554       1 route_controller.go:213] Created route for node epsilon-master-c3 10.244.0.0/24 with hint a673ed19-0712-4e3a-b063-bb76a4c51d80 after 2.301973558s
I1230 16:03:34.253224       1 route_controller.go:213] Created route for node epsilon-master-c2 10.244.1.0/24 with hint 32b5ff8a-f938-4b0b-a7d7-b7bfecb0fa84 after 4.088432355s
I1230 16:03:50.133216       1 route_controller.go:193] Creating route for node epsilon-master-c3 10.244.0.0/24 with hint a673ed19-0712-4e3a-b063-bb76a4c51d80, throttled 1.774µs
I1230 16:03:50.133216       1 route_controller.go:193] Creating route for node epsilon-master-c1 10.244.2.0/24 with hint 6503ceb9-b2d0-4d7e-b74d-6d55061cd818, throttled 952ns
I1230 16:03:50.133230       1 route_controller.go:193] Creating route for node epsilon-master-c2 10.244.1.0/24 with hint 32b5ff8a-f938-4b0b-a7d7-b7bfecb0fa84, throttled 561ns
I1230 16:03:51.478959       1 route_controller.go:213] Created route for node epsilon-master-c1 10.244.2.0/24 with hint 6503ceb9-b2d0-4d7e-b74d-6d55061cd818 after 1.345740011s
I1230 16:03:52.345804       1 route_controller.go:213] Created route for node epsilon-master-c3 10.244.0.0/24 with hint a673ed19-0712-4e3a-b063-bb76a4c51d80 after 2.212585214s
I1230 16:03:54.413706       1 route_controller.go:213] Created route for node epsilon-master-c2 10.244.1.0/24 with hint 32b5ff8a-f938-4b0b-a7d7-b7bfecb0fa84 after 4.280480604s
```

**Comment by mfrister** [comment]
Hey :)

I have a few questions, so I can better understand the problem:

1. For how long does the issue persist? Does it stop a few minutes (up to 10 minutes) after the last node replacement?
2. Do you use any additional networking layer (CNI plugins)?
3. Can you please provide a log of the hetzner-cloud-controller-manager? The provided log shows the Kubernetes controller manager output.

**Comment by vitobotta** [comment]
Hi @mfrister , sorry for the late reply, for some reason I haven't received notifications of updates here in the meantime. 

In the meantime I have torn down that cluster and created another one. 

With this new cluster the cloud controller manager is not creating/deleting routes, but I still have some weird message printed in the log every second or so. There's an issue about it opened by someone having the same problem here https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/107

**Comment by mfrister** [comment]
Hey @vitobotta, I've created #165 for your other issue.

I assume the route issue no longer appears, closing. Please comment if it reappears.

/close
