### ISSUE TITLE
Update node's providerID after server recreation

### ISSUE THREAD

**Issue by uykusuz** [hetznercloud/hcloud-cloud-controller-manager#146]
Hi ccm Team!

We have the following use case:
* snapshot server
* delete server
* create server from snapshot

In that case, with CCM installed, CCM won't update the node's `providerID` with the new server ID. 
This won't correctly update the load balancers anymore, because the server under the old ID can't be found anymore.

I tried updating the node's `providerID` manually, but it said `spec.providerID: Forbidden: node updates may not change providerID except from "" to valid`.

How can we make this possible?

We could rejoin the worker nodes to the cluster. But the master node will continue to have this problem.

**Comment by identw** [comment]
It's impossible. By design: https://github.com/kubernetes/kubernetes/issues/51596.
Try to remove the node from the cluster and restart kubelet on it.

**Comment by LKaemmerling** [comment]
Updating the providerID is not intended by the k8s spec. You should delete/remove the node and then let it rejoin (like @identw wrote).
