### ISSUE TITLE
node not initialized: failed to find kubelet node IP from cloud provider

### ISSUE THREAD

**Issue by uykusuz** [hetznercloud/hcloud-cloud-controller-manager#147]
Hi ccm Team!

I just bootstrapped a single node k8s cluster using hetzner's debian 10 image, did a dist-upgrade and with cilium 1.9.1 as CNI. I followed the instructions on [deploy with networks](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md) to set it up. 

But the node keeps the taint for being uninitialized. CCM complains with the following:

```
E0118 12:45:34.587422       1 node_controller.go:370] failed to initialize node test at cloudprovider: failed to find kubelet node IP from cloud provider
```

but on the node the required annotation is present:
```
alpha.kubernetes.io/provided-node-ip: 10.0.0.6
```

I tried restarting CCM (perhaps then a refreshed set of node annotations is picked up), that doesn't help.

Do you have any clues what might be happening here?

**Comment by uykusuz** [comment]
Sorry for the spam. The hcloud secret was wrong and this is how it told me that.

**Comment by mway-niels** [comment]
I had the same issue. For me the solution was to provide the `HCLOUD_NETWORK` environment variable.

**Comment by 53rg3** [comment]
Same. And setting `HCLOUD_NETWORK` solved it for me as well. The problem in my case is that I'm starting `kubelet` with `--node-ip` to use the private network which the hcloud cloud management controller manager or however that thing is called does not like. 

The value is the name of your private network in Hetzner and is stored in the secret `hcloud` at the key `network` (see [here](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/deploy_with_networks.md)). You need to add it to the Deployment like this:
```
- name: HCLOUD_NETWORK
  valueFrom:
    secretKeyRef:
      name: hcloud
      key: network
```
See [ccm-networks.yaml](https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.12.1/ccm-networks.yaml). I used the basic deployment without networks support and it seems to work. Using Cilium as network provider.
