### ISSUE TITLE
Support for mixed service types

### ISSUE THREAD

**Issue by WebSpider** [hetznercloud/hcloud-cloud-controller-manager#148]
Hi!

Currently the service type is fixed for all ports on a service, by use of an annotation on the service. 
This request is to add support for mixed service types.

Use case:

I have a Kubernetes cluster attached to this load-balancer. This kubernetes cluster is using nginx-ingress to service webtraffic. Ideal setup for this would be service type http/https.

I also use the tcp configmaps to grant access to TCP services, for instance a MySQL server that's also running on the same kubernetes cluster. This would obviously have to be TCP service type.

Currently, using hcloud-cloud-controller, this cannot be setup, while this can easily be setup using the Hetzner cloud webinterface.

**Comment by identw** [comment]
Do you want to create one service for nginx ingress and mysql? I think this is a bad idea. It should be two different services in kubernetes with different selectors.

**Comment by WebSpider** [comment]
I want one loadbalancer (connected to nginx-ingress) to handle all the incoming traffic, which then gets redistributed to the correct kubernetes services using tcp/udp configmaps.
