### ISSUE TITLE
LoadBalancer error message: ... use private ip: missing network id

### ISSUE THREAD

**Issue by morphace** [hetznercloud/hcloud-cloud-controller-manager#150]
I tried to set the annotation: load-balancer.hetzner.cloud/use-private-ip: 'true'

However my NGINX ingress controller stays in state Pending and I get the following event.

Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: use private ip: missing network id

What did I miss?

I intend to make back end service available only through the public IP of the LB and I hoped this would be the setting to achieve this.

**Comment by morphace** [comment]
bump...

**Comment by LKaemmerling** [comment]
Hey @morphace,

when you want to use `use-private-ip` you need to make sure that the LB is within the same network and your cluster is using our Hetzner Cloud Networks (the Cloud Controller Manager should control the Network).

**Comment by morphace** [comment]
Hey @LKaemmerling 

Thanks for your answer and support - I was not aware that I need to deploy the networks support.

Nevertheless, I have a hard time getting the LB stuff working. I'm trying to get NGINX Ingress to work with it and 2 masters and it's doing weird things. I'm experimenting.

Is there a way to prevent the LB being deleted (besides activating protection) when I remove the Ingress deployment?

**Comment by LKaemmerling** [comment]
@morphace in this case you should enable the protection, otherwise it is always deleted. You can then use the `name` annotation to reuse the LB with the given name.

As the main issue was solved I will also close the issue. If you encounter the same problem again feel free to write again under this issue.

**Comment by sooby18** [comment]
Hey @LKaemmerling

I tried to do  enable the protection, it doesn't work. produced by detach_from_network
