### ISSUE TITLE
Loadbalancer does not update health check port

### ISSUE THREAD

**Issue by mnordstr** [hetznercloud/hcloud-cloud-controller-manager#161]
Hi,

I've deployed a cluster on hcloud using Kubeone and we are using Istio ingressgateways which create LBs on Hetzner. cloud-controller-manager v1.8.1.

Possibly related issues https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/87 and https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/93

Our ingress gateway has the following hcloud annotations:
```
load-balancer.hetzner.cloud/location: hel1
load-balancer.hetzner.cloud/use-private-ip: "true"
load-balancer.hetzner.cloud/disable-private-ingress: "true"
```

When the loadbalancer is created, everything works fine. When our cluster scales, the target ports on the loadbalancer changes and the hcloud loadbalancer is updated automatically with the new ports. However, the health check ports are left as is and because of that the health checks fail leading to the service becoming unavailable.

I can fix it manually by
1. Deleting the ingress gateway and recreating it, or
2. Manually editing the health check ports through the hcloud portal to match the new target ports.

Is there something I'm missing, shouldn't the health check ports be automatically updated by the controller as well?

Regards,
Mattias Nordstrom

**Comment by LKaemmerling** [comment]
Hey @mnordstr,

can you provide us with the log lines from the cloud controller manager when you rescale the cluster?

**Comment by mnordstr** [comment]
Hi @LKaemmerling ,

Here are the log lines (there are actually two loadbalancers, the eastwest one is causing the issues):

```
I0303 10:08:18.229845       1 load_balancers.go:175] "update Load Balancer" op="hcloud/loadBalancers.UpdateLoadBalancer" service="istio-eastwestgateway" nodes=[REDACTED-pool1-574b465f5d-4dkk6 REDACTED-pool1-574b465f5d-bq2q5 REDACTED-pool1-574b465f5d-q75n5 REDACTED-pool2-87755f9cb-gt6jj REDACTED-pool2-87755f9cb-jbqnf]
I0303 10:08:18.849389       1 load_balancer.go:368] "remove target" op="hcops/LoadBalancerOps.ReconcileHCLBTargets" service="istio-eastwestgateway" targetName=""
I0303 10:08:20.350447       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15021 loadBalancerID=REDACTED061
I0303 10:08:21.566948       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15443 loadBalancerID=REDACTED061
I0303 10:08:22.999508       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15012 loadBalancerID=REDACTED061
I0303 10:08:24.189001       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15017 loadBalancerID=REDACTED061
I0303 10:08:25.497620       1 load_balancers.go:175] "update Load Balancer" op="hcloud/loadBalancers.UpdateLoadBalancer" service="istio-ingressgateway" nodes=[REDACTED-pool1-574b465f5d-4dkk6 REDACTED-pool1-574b465f5d-bq2q5 REDACTED-pool1-574b465f5d-q75n5 REDACTED-pool2-87755f9cb-gt6jj REDACTED-pool2-87755f9cb-jbqnf]
I0303 10:08:25.497676       1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"istio-system", Name:"istio-eastwestgateway", UID:"REDACTED-eb0258b6f06c", APIVersion:"v1", ResourceVersion:"865006", FieldPath:""}): type: 'Normal' reason: 'UpdatedLoadBalancer' Updated load balancer with new hosts
I0303 10:08:26.115701       1 load_balancer.go:368] "remove target" op="hcops/LoadBalancerOps.ReconcileHCLBTargets" service="istio-ingressgateway" targetName=""
I0303 10:08:27.410520       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15021 loadBalancerID=REDACTED660
I0303 10:08:28.548731       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=80 loadBalancerID=REDACTED660
I0303 10:08:29.834917       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=443 loadBalancerID=REDACTED660
I0303 10:08:31.055984       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15012 loadBalancerID=REDACTED660
I0303 10:08:32.357632       1 load_balancer.go:439] "update service" op="hcops/LoadBalancerOps.ReconcileHCLBServices" port=15443 loadBalancerID=REDACTED660
I0303 10:08:33.578410       1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"istio-system", Name:"istio-ingressgateway", UID:"REDACTED-58e53d07dbbb", APIVersion:"v1", ResourceVersion:"19761", FieldPath:""}): type: 'Normal' reason: 'UpdatedLoadBalancer' Updated load balancer with new hosts
```

**Comment by mnordstr** [comment]
What I've done now to make it work is I've added the following annotation to the LB:

```
load-balancer.hetzner.cloud/health-check-port: "10250"
```

This checks the kubelet port so I know the host is there, but preferably of course the actual service would be checked.

**Comment by LKaemmerling** [comment]
Hey @mnordstr,

i tried to reproduce it but it always works in our test clusters. Which cloud controller manager version do you have? Can you try it again with the latest master ("dev") release? 
Without Networks: https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/dev-ccm.yaml
With Networks: https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/dev-ccm-networks.yaml
