### ISSUE TITLE
Prevent use of eth0

### ISSUE THREAD

**Issue by ambis** [hetznercloud/hcloud-cloud-controller-manager#163]
Hello,

I run my VPS's with eth0 completely disabled, routing traffic out via another machine via private network. Much like [this](https://community.hetzner.com/tutorials/how-to-route-cloudserver-over-private-network-using-pfsense-and-hcnetworks), but using different software on the router machine.

If I run this CCM, it updates the external eth0 ip as the public node ip, replacing it's original 10.0.0.x ip.

This causes eg. ingress-nginx with hostNetwork to be completely bork.

It would be nice if there was a way to prevent this from happening.

**Comment by beatkind** [comment]
I more or less running into the same problem. How is it about setting the "--node-ip" flag in the kubelet service?

On my side the flag is recognized but only in the way that there is a new annotation on the node itself:
`alpha.kubernetes.io/provided-node-ip: 10.1.1.11`

That causes a problem not only with the ingress-nginx but also with the metrics server if you have the API server setup to listen to the private IP.

**Comment by LKaemmerling** [comment]
The Cloud Controller Manager does not know something about the underlying networking interfaces, the CNI plugin you use (& Kubernetes) are in charge of this, so I'm sorry there is nothing we can do here. The Cloud Controller Manager just passes a few information to k8s (https://kubernetes.io/docs/concepts/architecture/cloud-controller/#node-controller), K8s then decides what it does with that information.

**Comment by LKaemmerling** [comment]
As there is nothing we (as cloud controller manager)  can do here I will close the issue. Feel free to reopen it again when you think there is something we can/should do.
