### ISSUE TITLE
Doc Request: Clarify why one would use ccm-network

### ISSUE THREAD

**Issue by ambis** [hetznercloud/hcloud-cloud-controller-manager#164]
It is said the ccm-network version works differently, but not *how*.

When using CCM, are the pods and services then themselves visible to the Hetzner private network?

You recommend cilium, but how about Calico & WeaveNet, would they work just as well? Considering one needs to adjust cilium with quite a few custom options.

**Comment by philwelz** [comment]
+1

**Comment by beatkind** [comment]
+1

**Comment by LKaemmerling** [comment]
When you use the Cloud Controller Manager with networks support, the CCM is in favor of allocating the IPs (& setup the routing) (Docs: https://kubernetes.io/docs/concepts/architecture/cloud-controller/#route-controller). The CNI plugin you use needs to support this k8s native functionality (Cilium does it, I don't know about Calico & WeaveNet), so basically you use the Hetzner Cloud Networks as the underlying networking stack. 

When you use the CCM without Networks support it just disables the RouteController part, all other parts work completely the same. Then just the CNI is in charge of making all the networking stack things. Using the CCM with Networks support has the benefit that your node is connected to a private network so the node doesn't need to encrypt the connections and you have a bit less operational overhead as you don't need to manage the Network.

**Comment by LKaemmerling** [comment]
I guess the question is answered or? If not feel free to reopen the issue again.
