### ISSUE TITLE
Get X-Real-IP header from Load Balancer

### ISSUE THREAD

**Issue by jaumecornado** [hetznercloud/hcloud-cloud-controller-manager#171]
It seems load balancer does not respect _X-Real-Ip_ and _X-Forwarded-For_ headers and always getting LB ip into those values.

There is a way to pass it through?

**Comment by LKaemmerling** [comment]
Hey @jaumecornado,

i guess your service is a raw TCP service or? You could try to set the `load-balancer.hetzner.cloud/protocol` annotation to http/(https). Link to FAQ: https://docs.hetzner.com/cloud/load-balancers/faq/#do-load-balancers-forward-special-http-headers

**Comment by jaumecornado** [comment]
With proxprotocol works perfectly. Added `load-balancer.hetzner.cloud/uses-proxyprotocol: "true"` to fix
