### ISSUE TITLE
Handling of root servers: an idea

### ISSUE THREAD

**Issue by uykusuz** [hetznercloud/hcloud-cloud-controller-manager#172]
Dear Hetzner-Team,

This is a follow up on [this ticket](https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/133).

[We made it work for our use case.](https://github.com/hetznercloud/hcloud-cloud-controller-manager/compare/master...xelonic:root-server-support)

Are there any chances any solution in this direction can be implemented in the CCM? I didn't want to open a PR, because it's by no means a full solution, just an idea.

If you think it's bad please let me know why.

**Comment by LKaemmerling** [comment]
Hey @uykusuz,

we thought about your solution, your solution is quite good but we don't think that it fits well in most setups. We currently have a few issues with supporting dedicated servers fully in the cloud-controller-manager. Our plan is to support them full-blown (so with network routes), but unfortunately, there are a lot of technical difficulties we have on the router level. We still search for a solution there together with our network department. As we don't want to make a "half" solution (like: Just ignore the dedicated servers) first and then later one introduce breaking changes with the full solution, we decided to wait until the investigations are finished. I'm sorry that I don't have any other feedback for you.

**Comment by uykusuz** [comment]
Sounds good to me! I'm glad that you're working on a solution!

**Comment by maaft** [comment]
Hey, anything I can do to provision Loadbalancers to my root servers automatically via ccm **right now**?
