### ISSUE TITLE
rDNS on LoadBalancer

### ISSUE THREAD

**Issue by AlexMe99** [hetznercloud/hcloud-cloud-controller-manager#175]
I just went through the configuration options of the loadbalancer. I was not able to find a way to adjust the reverse dns entry. I know that it can be done easily for normal server instances. Is there a way to do it also with the load-balancers?

**Comment by LKaemmerling** [comment]
Hey @AlexMe99,

our Load Balancers currently do not support rDNS entries. I added a +1 to our internal "wishes" list.

**Comment by elcomtik** [comment]
@LKaemmerling Currently, I see that, I can set this in the console. Is it still unsupported by CCM?

**Comment by dominic-p** [comment]
I'm curious about this as well. Can we configure rDNS on CCM generated load balancers at this point?

**Comment by apricote** [comment]
Hey :) This is supported in the CCM since #274, first released in 1.13.0.
