### ISSUE TITLE
unexpected EOF - error listing routes: hcloud/ListRoutes

### ISSUE THREAD

**Issue by StarpTech** [hetznercloud/hcloud-cloud-controller-manager#176]
Hello, we experience an outage of our kubernetes cluster due to an error in the cloud controller.
```
I0321 18:05:44.022024 1 event.go:278] Event(v1.ObjectReference{Kind:"Service", Namespace:"production", Name:"traefik", UID:"6e7bcfe4-5425-428a-a46a-b5d06cde3c26", APIVersion:"v1", ResourceVersion:"44779555", FieldPath:""}): type: 'Normal' reason: 'EnsuredLoadBalancer' Ensured load balancer
E0322 21:11:00.840024 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/reloadNetwork: Get "https://api.hetzner.cloud/v1/networks/181010": unexpected EOF
I0324 00:39:12.652092 1 log.go:181] http: TLS handshake error from 92.63.197.21:54480: tls: first record does not look like a TLS handshake
I0324 00:39:12.673980 1 log.go:181] http: TLS handshake error from 92.63.197.21:54910: tls: first record does not look like a TLS handshake
E0330 09:03:33.736562 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP: hcops/AllServersCache.getCache: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": context deadline exceeded
E0330 09:03:43.288938 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP: hcops/AllServersCache.getCache: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": context deadline exceeded
E0330 09:04:12.950591 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP: hcops/AllServersCache.getCache: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": context deadline exceeded
E0330 09:05:12.952105 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/reloadNetwork: Get "https://api.hetzner.cloud/v1/networks/181010": unexpected EOF
E0330 09:05:24.865286 1 route_controller.go:118] Couldn't reconcile node routes: error listing routes: hcloud/ListRoutes: hcloud/hcloudRouteToRoute: hcops/AllServersCache.ByPrivateIP: hcops/AllServersCache.getCache: Get "https://api.hetzner.cloud/v1/servers?page=1&per_page=50": context deadline exceeded
I0403 15:02:54.209484 1 log.go:181] http: TLS handshake error from 91.241.19.244:65492: tls: first record does not look like a TLS handshake
I0404 04:04:57.289065 1 log.go:181] http: TLS handshake error from 91.241.19.229:63342: tls: first record does not look like a TLS handshake
I0404 05:38:26.577817 1 log.go:181] http: TLS handshake error from 91.241.19.229:65443: tls: first record does not look like a TLS handshake
```

**Comment by StarpTech** [comment]
After ~30 minutes and restarting the controller several times it works again. This is pretty bad.

**Comment by fhofherr** [comment]
Hi @StarpTech,

thanks for the report. The log messages you posted seem to indicate some kind of network related issue and not a problem with the CCM. In this case the CCM can't do much more than return an error and retry after a certain time.

Based on the timestamps in the logs you have posted the retry seems to have worked. The log messages start at about 18:00 and end at about 05:40. There are rather big gaps in between where nothing seems to have been logged that indicates an error. I therefore presume that the CCM worked as expected during those gaps. Based on the logs I cannot tell whether the restarts of the CCM helped to fix the issue.

Just to give us a chance to dig deeper: when did the outage occur? Did it span the whole time of the log messages? How did you become aware of the outage? Even with a complete CCM failure, the cluster should have continued working. Did you notice any other strange behavior with your cluster during that time? Things like not being able to SSH into the nodes, or similar?

**Comment by StarpTech** [comment]
Hi @fhofherr, during the outage the hetzner load balancer has marked several targets as unhealthy. This resulted in a downtime of our application. Traefik, Canal (CNI) and Loki (daemonset) have restarted several times.

> when did the outage occur

Around 8:00 pm

> How did you become aware of the outage

Our reverse proxy has stopped without an error.

> Even with a complete CCM failure, the cluster should have continued working

Possible that the CCM reports wrong targets to the load balancer?

> Things like not being able to SSH into the nodes, or similar?

No

Thanks!

**Comment by fhofherr** [comment]
> Possible that the CCM has reported wrong targets to the load balancer?

Unlikely. According to the logs the CCM was not able to access our API. So it had no chance to obtain anything.

Another thing we noticed: a `whois` on the IPs `92.63.197.21` and `91.241.19.244` from the log snippet above shows they do not belong to Hetzner. Yet, somehow the CCM seems to have tried to access those IPs. Did you configure anything on your side that would cause it to do that? Things like DNS, or the `HCLOUD_ENDPOINT` environment variable would come to mind.

You seem to also have opened a support ticket with us related to this issue. It may be better to answer there if this is sensitive information.

**Comment by StarpTech** [comment]
@fhofherr I'm only interested in the condition of why we weren't able to access the hetzner API.

> Did you configure anything on your side that would cause it to do that? Things like DNS, or the HCLOUD_ENDPOINT environment variable would come to mind.

I didn't configure anything in that direction.

**Comment by fhofherr** [comment]
Based on you locks it is hard to tell and presumably not related to the cloud controller manager itself. It seems more likely that what you experienced with the cloud controller manager was a symptom of something else. I would therefore like to ask you to continue further discussion in the internal ticket you opened. As such I'm closing this issue.
