### ISSUE TITLE
Is it possible to connect floating IP to a Load Balancer / Ingress?

### ISSUE THREAD

**Issue by hershkoy** [hetznercloud/hcloud-cloud-controller-manager#177]
As far as I can understand it is possible with GCE, here is an example:
https://gist.github.com/pepijnblom/176e31c839ebc73e386113e8b76ee3a6#file-ingress-yaml

Is a similar option available in hcloud? I have only seen an option to connect floating IP to a server, not to a load balancer. 
My kubernetes cluster is using load balancer and ingress-nginx. If I have a http://example.com domain, how can I redirect it to the kubernetes cluster?

**Comment by LKaemmerling** [comment]
Hey @hershkoy,

currently, it is not possible to assign a Floating IP to a Load Balancer. I added a +1 to our internal feature whishes list from you.
