### ISSUE TITLE
Add Networks support

### ISSUE THREAD

**Issue by LKaemmerling** [hetznercloud/hcloud-cloud-controller-manager#19]

**Comment by LKaemmerling** [comment]
I am pleasured to "announce" that we have now a first beta ready.

You can see all the changes in #20.

We would like to get some feedback before releasing this.

**Please don't use this for a production environment at the moment!**

**But how can you use the networks?**

1. Create a Network via our CloudConsole (or via CLI)
2. Download the new deployment file with networks support https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/20/files#diff-5664dce30eb7444c8914c3181f868162
3. Change the `cluster-cidr` to your pod range
4. Create a new secret with your token `kubectl -n kube-system create secret generic hcloud --from-literal=token=<hcloud API token>`
4. Create a new secret with the network identifier `kubectl -n kube-system create secret generic hcloud --from-literal=network=<hcloud Network_ID_or_Name>`
5. Deploy your changed deployment 
6. Deploy a CNI (like Cilium `kubectl create -f https://raw.githubusercontent.com/cilium/cilium/v1.5/examples/kubernetes/<kubernetes-version>/cilium.yaml` - please replace `<kubernetes-version>` with your version like `1.15`)

You should now see the Internal IPs on your nodes and you should see the routes in the CloudConsole.

**Comment by eino-makitalo** [comment]
I made those secrets in one command because kubernet said that secret already created...
kubectl -n kube-system create secret generic hcloud --from-literal=token=<cloudAPI> --from-literal=network=<my networkname>   
I did not find any Network ID so I gave the name in console... (using hetzner cloud console)

**Comment by eino-makitalo** [comment]
step 2 download file from: https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/implement-networks/deploy/development-networks.yaml  is better :-)

**Comment by LKaemmerling** [comment]
@all We will release the new cloud controller manager version within the next week.
