### ISSUE TITLE
Support for private networks

### ISSUE THREAD

**Issue by vladimirtiukhtin** [hetznercloud/hcloud-cloud-controller-manager#199]
Controller does not seem to have support for private networks. It discovers only ExternalIP even if workers are attached to private network too. Setting --node-ip on kubelet breaks the controller completely - it cannot find the node anymore :(

**Comment by LKaemmerling** [comment]
Hey @vladimirtiukhtin,

the cloud controller manager has support for networks since the beginning of the networks feature. Have a look here to see how to deploy the CCM with networks support: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md

**Comment by vladimirtiukhtin** [comment]
Thanks @LKaemmerling. Indeed it now recognizes nodes properly, however unless kube-controller-manager has "--cluster-cidr" and "--allocate-node-cidrs" flags hcloud controller does not turn kubelet in ready state. What's the purpose of specifying the same flags on hcloud controller then if it does not care much?
