### ISSUE TITLE
hcloud provider network start fail 

### ISSUE THREAD

**Issue by Macbet** [hetznercloud/hcloud-cloud-controller-manager#23]
Hello all. 
When i try start hcloud-cloud-controller-manager with network support i get this error logs 

> kubectl logs -f hcloud-cloud-controller-manager-7f59845fb6-smtwn 
> 
> Flag --allow-untagged-cloud has been deprecated, This flag is deprecated and will be removed in a future release. A cluster-id will be required on cloud instances.
> ERROR: logging before flag.Parse: W0916 13:48:44.704964       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> ERROR: logging before flag.Parse: W0916 13:48:44.712289       1 controllermanager.go:108] detected a cluster without a ClusterID.  A ClusterID will be required in the future.  Please tag your cluster to avoid any future issues
> ERROR: logging before flag.Parse: W0916 13:48:44.713737       1 authentication.go:55] Authentication is disabled
> ERROR: logging before flag.Parse: I0916 13:48:44.713808       1 insecure_serving.go:49] Serving insecurely on [::]:10253
> ERROR: logging before flag.Parse: I0916 13:48:44.717345       1 node_controller.go:89] Sending events to api server.
> ERROR: logging before flag.Parse: E0916 13:48:44.721045       1 controllermanager.go:240] Failed to start service controller: the cloud provider does not support external load balancers
> ERROR: logging before flag.Parse: I0916 13:48:44.721880       1 pvlcontroller.go:107] Starting PersistentVolumeLabelController
> ERROR: logging before flag.Parse: I0916 13:48:44.721989       1 controller_utils.go:1025] Waiting for caches to sync for persistent volume label controller
> ERROR: logging before flag.Parse: I0916 13:48:44.822307       1 controller_utils.go:1032] Caches are synced for persistent volume label controller
> ERROR: logging before flag.Parse: I0916 13:48:45.020493       1 route_controller.go:102] Starting route controller
> ERROR: logging before flag.Parse: I0916 13:48:45.020554       1 controller_utils.go:1025] Waiting for caches to sync for route controller
> ERROR: logging before flag.Parse: E0916 13:48:45.060905       1 node_controller.go:161] providerID should start with hcloud://: 3295411
> ERROR: logging before flag.Parse: I0916 13:48:45.120773       1 controller_utils.go:1032] Caches are synced for route controller
> ERROR: logging before flag.Parse: E0916 13:48:45.121072       1 runtime.go:66] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:72
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:65
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:51
> /usr/local/go/src/runtime/panic.go:522
> /usr/local/go/src/runtime/panic.go:82
> /usr/local/go/src/runtime/signal_unix.go:390
> /maschine-controller/src/hcloud/routes.go:30
> /maschine-controller/src/hcloud/routes.go:58
> /go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:128
> /go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:119
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:133
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:134
> /go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:98
> /usr/local/go/src/runtime/asm_amd64.s:1337
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> 	panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1087f97]
> 
> goroutine 126 [running]:
> k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/runtime/runtime.go:58 +0x105
> panic(0x161ed00, 0x29720f0)
> 	/usr/local/go/src/runtime/panic.go:522 +0x1b5
> github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*routes).reloadNetwork(0xc0004ba860, 0x1ae5000, 0xc00009c018, 0x203000, 0xc0002af960)
> 	/maschine-controller/src/hcloud/routes.go:30 +0x37
> github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud.(*routes).ListRoutes(0xc0004ba860, 0x1ae5000, 0xc00009c018, 0x18498ad, 0xa, 0xc00088f610, 0x44bdb6, 0xc000567880, 0x7, 0x10)
> 	/maschine-controller/src/hcloud/routes.go:58 +0x5a
> k8s.io/kubernetes/pkg/controller/route.(*RouteController).reconcileNodeRoutes(0xc0002491f0, 0x44bb4b, 0xc000120738)
> 	/go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:128 +0x73
> k8s.io/kubernetes/pkg/controller/route.(*RouteController).Run.func1()
> 	/go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:119 +0x2e
> k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc0004ccde0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:133 +0x54
> k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0004ccde0, 0x2540be400, 0x0, 0x100, 0x0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:134 +0xf8
> k8s.io/apimachinery/pkg/util/wait.NonSlidingUntil(0xc0004ccde0, 0x2540be400, 0x0)
> 	/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20180621070125-103fd098999d/pkg/util/wait/wait.go:98 +0x4d
> created by k8s.io/kubernetes/pkg/controller/route.(*RouteController).Run
> 	/go/pkg/mod/k8s.io/kubernetes@v1.11.1/pkg/controller/route/route_controller.go:118 +0x1f2

kubernetes version 1.15.3
cni flannel

**Comment by LKaemmerling** [comment]
Looks like the controller can not find the network. Have you created a secret containing the network ID or Name? (`kubectl -n kube-system create secret generic hcloud --from-literal=network=<hcloud Network_ID_or_Name>`) ?

https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/19#issuecomment-512850269

**Comment by Macbet** [comment]
Yes, of course, true, I did not create it but updated it and now in this secret there are 2 fields token & network, what else can you try to run ?

**Comment by Macbet** [comment]
sorry< it was my typo error, can y
