### ISSUE TITLE
Use load-balancer for multiple services

### ISSUE THREAD

**Issue by dcardellino** [hetznercloud/hcloud-cloud-controller-manager#232]
Hello together,

i use hcloud-ccm for my k8s deployment. I recently have deployed nginx-ingress controller with the following annotations:

```
load-balancer.hetzner.cloud/location: fsn1
load-balancer.hetzner.cloud/name: ingress
load-balancer.hetzner.cloud/use-private-ip: "true"
load-balancer.hetzner.cloud/disable-private-ingress: "true"
```

So a load-balancer gets created in hetzner cloud console.  When i use this to expose websites on port 80/443, this works perfectly.

I want to re-use this load-balancer to also expose an openldap deployment on port 389. 
I read some issues here to use the annotation
`load-balancer.hetzner.cloud/name:` or `load-balancer.hetzner.cloud/id` but when i apply the k8s manifests, the ccm deletes the existing services on the load balancer and adds 389/636 for ldap/ldaps.

Can you give me an advice how to get a solution for this?

thanks,

Dominic

**Comment by LKaemmerling** [comment]
Hey @dcardellino,

you can only use one k8s service (with multiple ports) per Load Balancer. The Cloud Controller Manager always tries to reach the state defined in the specific service and deletes everything else.

**Comment by stevek-pro** [comment]
You need to load balance with an ingress-controller, from any vendor. I am working on this but failling. I will open a seperate issue on this. If a Hetzner member could provide a working setup for ingress-nginx namespaced controller.

**Comment by talex-de** [comment]
You can use Traefik as Ingress Controller.

For a working example see my public Git repo from Meetups here:
