### ISSUE TITLE
Global default for IPv6 on LBs 

### ISSUE THREAD

**Issue by mstarostik** [hetznercloud/hcloud-cloud-controller-manager#233]
Hello,

as mentioned in the pkg docs, the annotation `load-balancer.hetzner.cloud/ipv6-disabled` can be used to remove the IPv6 address from a LoadBalancer service and as hinted there, it's pretty much required when running external-dns.
Would be nice to have an ENV var to disable the v6 address by default, similar to how `HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS`, gets rid of the private IP.

Thanks,
Malte

**Comment by fynluk** [comment]
Hey Malte, hey community,

I submitted an approach to fix this 'problem'.
In my opinion there should be the possibility to enable or disable ipv6.
Please have a look at the pr and give me feedback

**Comment by LKaemmerling** [comment]
Hey @mstarostik,

your MR was merged, so this will be available with the next release version (or already with the latest master/dev version).
