### ISSUE TITLE
No matches for kind "Deployment" in version "extensions/v1beta1"

### ISSUE THREAD

**Issue by HenkVanMaanen** [hetznercloud/hcloud-cloud-controller-manager#24]
Kubernetes v1.16.1

I get the error `no matches for kind "Deployment" in version "extensions/v1beta1"` with the following command: `kubectl apply -f https://raw.githubusercontent.com/hetznercloud/hcloud-cloud-controller-manager/master/deploy/v1.4.0-networks.yaml`

Is this my fault or is this a bug?

**Comment by Macbet** [comment]
in kubernetes 1.16 kind "Deployment " move from "extensions/v1beta1"  "apps/v1" need update manifest

**Comment by HenkVanMaanen** [comment]
Yes that fixes the problem partially, however the following error shows up `missing required field "selector" in io.k8s.api.apps.v1.DeploymentSpec;`
