### ISSUE TITLE
Question: UDP load balancer support

### ISSUE THREAD

**Issue by rpahli** [hetznercloud/hcloud-cloud-controller-manager#252]
Hello Hetzner Team,

we use hetzner for our k8s Cluster(s). But we also need support for UDP traffic Load Balancing. 

Is there any plan to support UDP Load Balancers?
Or is there any workarround to loadbalance UDP traffic over multible k8s nodes?

**Comment by fmendez89** [comment]
Hi @rpahli, did you manage to get udp working?

**Comment by rpahli** [comment]
Currently it works only with NodePort. So you can use nodePort with an internal LB service like Haproxy. This is not the best solution but I think currently the only working solution.

**Comment by fmendez89** [comment]
Hi @rpahli, 
we ended up using nginx as a LB with a floating IP, not the best solution IMO too. So... waiting for the UDP support from Hetzner.
Thanks for the tip.

**Comment by pasztorl** [comment]
Hi! There is any news about planning to extend the loadblancer with udp support?

**Comment by Sporesirius** [comment]
Why close?

**Comment by apricote** [comment]
The hcloud-cloud-controller-manager can only implement features that are actually available in the Hetzner Cloud. As there is no UDP support for Hetzner Cloud Load Balancers, it does not make sense for us to keep this issue open.

I have added the "votes" from pasztorls comment to our internal feedback tool.

**Comment by pasztorl** [comment]
I hope Hetzner will support udp loadbalancers soon :)

**Comment by Rohmilchkaese** [comment]
No updates yet ?

**Comment by vladimirtiukhtin** [comment]
Most wanted for HTTP/3, have to AWS because of that

**Comment by apricote** [comment]
@vladimirtiukhtin I have added a vote to the HTTP3 feature on our internal feedback tracker.

@Rohmilchkaese the best way to get informed about new features is the https://docs.hetzner.cloud/changelog, you can subscribe to an RSS/Atom feed for notifications.
