### ISSUE TITLE
Question: how do i install nginx ingress controller on my cluster

### ISSUE THREAD

**Issue by mabebrahimi** [hetznercloud/hcloud-cloud-controller-manager#253]
I installed the hcloud-cloud-controller-manager with [this](https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm-networks.yaml) file. and LoadBalancer service type works correctly.
Now how do I install the Hetzner compatible ingress controller?

**Comment by stevek-pro** [comment]
I used the one from the official documentation (see github page) from ingress-nginx. Installation worked flawlessly after appling the annotations geom Hetzner. 

It also provisions itself an LB and certs, but for me I cant get my webservice to be routed through to yet.

If you get routing and termination please feel free to share your Setup and Code.

**Comment by Giom-fm** [comment]
@stevek-pro 
Could you be a little more specific?
I just can't get the loadbanalcer to work in conjunction with nginx.

**Comment by fhofherr** [comment]
Closing as this seems not to be related to the cloud controller manager.

**Comment by stevek-pro** [comment]
@Giom-fm Thanks for posting those files, I will try them out and report back if this is reproducably working. 

May I ask what annotations you use, I am sure you don't use all. 

Also, may I also ask if you're now sucessfully run certs on your individual ingress resources? 

@fhofherr I'd say it is still controller manager related.
