### ISSUE TITLE
*much* clearer and easier to use documentation

### ISSUE THREAD

**Issue by tpo** [hetznercloud/hcloud-cloud-controller-manager#256]
Dear Hetzners,

please, please provide better docu. I've been a Linux admin for 20 years and a K8s admin for 3 but I am *unable* to understand and apply your [deployment](https://github.com/hetznercloud/hcloud-cloud-controller-manager#deployment) instructions to a vanilla [microk8s](http://microk8s.io/) setup (running out of the box [Calico](http://www.projectcalico.org/)). Your jargon kills me. There's too much technical detail that I have *no clue* about:

* flannel?
* kubeadm?
* needing to set up my own networking: `--pod-network-cidr=10.244.0.0/16`?
* deploying CNI?
* "When you use the CCM without Networks support it just disables the RouteController part" err - what does that imply?
* with or without networks support? I mean how would I reach the cluster running at Hetzner without network? Care to explain? Evidently the context of the matter isn't named, described and explained well, IMHO. 
* Kube-proxy mode IPVS and HCloud LoadBalancer? I do not know enough about kube-proxy and have no idea whether microk8s runs in IPVS mode.

 If Hetzner wants to attract people to run their K8s clusters at Hetzner (which I'd consider awesome!!!) then setting up an Ingress, that works with Hetzner's load balancer needs to get **much much much** easier, I'd recon. I mean *much* easier.

OK, I'm sorry I can't offer more than critique and thanks a lot for stretching your hand out towards the people trying to run k8s on your infrastructure. Maybe, after fighting with Ingress, Hetzner's LoadBalancer and cert-manager for three days I'll have another stab at getting hcloud-cloud-controller-manager to run at some later time.

Best greetings,
*t

PS: There's a Wiki in this git repo that however doesn't work. It'd be an opportunity for you folks to open the wiki up so maybe some users of the CCM could contribute their howto's there?

**Comment by stevek-pro** [comment]
I would like to help. Everything is quite shit as it is of now, radial candor sorry.

**Comment by fhofherr** [comment]
Hi, we are aware that there is room for improvement with respect to our docs. While there are a lot of customers that successfully use our kubernetes integrations documentation is something that could always be improved.

As for the wiki I'd like to make you aware of https://community.hetzner.com where we and our customers provide all kinds of tutorials for our products. Your contributions are welcome.
