### ISSUE TITLE
Newly created servers won't boot after initial creation

### ISSUE THREAD

**Issue by kev-ac** [hetznercloud/hcloud-cloud-controller-manager#264]
I've noticed a strange bug in relation to the creation of new nodes / servers. 
In some cases (maybe 1 in 10) a newly created server is not booting which prevents the cluster autoscaler to work properly. 

I can see the _"server.create"_ action logged in the Cloud Console as well as the created, but turned off server in the list. 

I noticed this behavior in Kubernetes version 1.21.7 but it also persists after updating to 1.22.4 (while executing rolling MachineDeployment update).

Is that something that could be related to the hcloud ccm or is it a bug in the hcloud infrastructure itself? 

Hcloud ccm version: v1.12.0

**Comment by fhofherr** [comment]
Hi @kev-ac,

just to be sure: the server itself is not accessible at all, even outside of K8S for example via SSH or the console in our web interface? 

In this case this sounds more like an issue with the infra structure and I would recommend opening a support ticket for your account.

**Comment by kev-ac** [comment]
Hi @fhofherr,

this is something I haven't checked. What I can tell you is that the servers state is "turned off" in the web interface, even after 10-15 minutes and after several reloads of the page.
Also the server won't come up in the K8S cluster so no communication seems to happen. 

I can check connectivity via ICMP / SSH or the web console when I stumble across this phenomenon again. 
But I will also open a support ticket and reference this issue. Maybe it is a known issue.

**Comment by kev-ac** [comment]
The support was able to find the reason for this problem. 
The server could not be connected to the private network on start. This results in the server being unable to start. 
It is a known issue and they are working on improving the situation. 

A workaround would be to create the server without a private network and attach it afterwards.
Is that something we could handle in the CCM until the Hcloud infrastructure team fixes the bug?

**Comment by fhofherr** [comment]
Sorry, for getting back to you so late. How do you create the servers before adding them to the cluster? I believe the safest bet would be to modify the way you create the servers to split up creation and network attaching.

The cloud-controller itself does not create servers. Also it does not seem like the [Instances](https://pkg.go.dev/k8s.io/cloud-provider#Instances) or the [InterfacesV2](https://pkg.go.dev/k8s.io/cloud-provider#InstancesV2) really allow to implement modifying instances in such a way. Depending on how your cluster is set-up it may not even be possible, as the servers need to be attached to the private network before they can join the cluster.
