### ISSUE TITLE
add environment variable for default load balancer type

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/hcloud-cloud-controller-manager#265]
Hi,

it would be great if additionally to the existing default settings for load balancers also the type could be set by default, avoiding to add the `load-balancer.hetzner.cloud/type` annotation to each load balancer service.

Best regards
Matthias

**Comment by crstin** [comment]
`load-balancer.hetzner.cloud/location` would also be very welcome or why not being able to set defaults for everything?

**Comment by MatthiasLohr** [comment]
There is an environment variable `HCLOUD_LOAD_BALANCERS_LOCATION`, are you searching for that? However, there is no equivalent for `load-balancer.hetzner.cloud/type`.

**Comment by crstin** [comment]
Just would like to to be able to set a default for the location without messing with the annotations. Why not make all config options available in such a way? There's gotta be a way.

**Comment by MatthiasLohr** [comment]
@LKaemmerling, any opinion on that?

**Comment by MatthiasLohr** [comment]
Can we please reopen this issue as it never has been discussed but also never was stale?
