### ISSUE TITLE
Please update deploy manifests to current image version

### ISSUE THREAD

**Issue by philipp1992** [hetznercloud/hcloud-cloud-controller-manager#266]
Hi,
the manifests in the deploy folder use outdated image versions.
Could you update them when you release a new version, so they can be used for gitops processes?

thanks and kind regards
Philipp

**Comment by LKaemmerling** [comment]
Hey @philipp1992,

this is intended. Please use the generated files from Github Releases. 
https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest

Thank you!
