### ISSUE TITLE
Nodes by default are tainted

### ISSUE THREAD

**Issue by sitamoni** [hetznercloud/hcloud-cloud-controller-manager#268]
I am new in k8s and have issue with Taints, i am trying to untaint the nodes with 
`kubectl taint node worker-1 node.cloudprovider.kubernetes.io/uninitialized=false:NoSchedule-`
when kubespray provisions my cluster with ansible-playbook. Is there any way to get the cluster nodes already untainted after creating it from hcloud-controller-manager cause it is default, i mean of courde editing a config file or workaround else.
I used also the [here](https://community.hetzner.com/tutorials/install-kubernetes-cluster).
I appreciate your help and advice.

**Comment by LKaemmerling** [comment]
Hey @sitamoni,

normally the Cloud Controller Manager is in charge of untainting them. When they have a taint this is normally an indication that the CCM can not process them, so please have a look at the CCM logs, maybe you find something there.

Please make sure:
- The Names of your k8s nodes should be the names of the servers in our cloud console
- The API Token you pass to the CCM needs to have access to the project where the servers are running.

**Comment by sitamoni** [comment]
Thanks for help it worked. The name in the cloud console should have been set same as ones of created with terraform in k8s.

**Comment by sitamoni** [comment]
Thanks for help it worked
