### ISSUE TITLE
Using ingress-nginx LB and helm chart on one directory

### ISSUE THREAD

**Issue by sitamoni** [hetznercloud/hcloud-cloud-controller-manager#273]
Hallo,
I used the inventory `home/$USER/kubespray/inventory/pro/hosts.yaml` lokal on PC to create my cluster of hetzner cloud servers in a project  Prod with playbook and then another project from hetzner cloud with another hcloud_Token in `home/$USER/kubespray/inventory/sta/hosts.yaml`
Now after installing kubernetes cluster and depolying both clusters. The command of kubectl works only fine with a one project prod and not with project sta. And also the following commands, that my kubernetes doesn't integrate with the hcloud-cloud controller manager.
i also considered right Tokens. Please advice.
```
kubectl -n kube-system create secret generic hcloud --from-literal=token=${GITLAB_ACCESS_TOKEN}

kubectl apply -f  https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/latest/download/ccm.yaml #integrate your Kubernets cluster with the Hetzner Cloud API.

kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/v1.6.0/deploy/kubernetes/hcloud-csi.yml

helm install nginx-controller -f ./helmcharts/ingress-nginx/values.yaml ingress-nginx/ingress-nginx
```
In addition  no LB is shown in Hetzner Cloud frontend. although secret,,, csi are successfully created

**Comment by dclayton77** [comment]
While not exactly the same as your problem, I wrote a blog on how to get a cluster, load balancer etc fully up an running.  You may be able to take some pointers from there to help with your problem.

https://dcse-ltd.co.uk/building-a-bare-metal-kubernetes-cluster-part-3-service-mesh-https-certificates-and-ingress/
