### ISSUE TITLE
Cloud controller + Core DNS issues

### ISSUE THREAD

**Issue by dclayton77** [hetznercloud/hcloud-cloud-controller-manager#275]
Hi, I have built a new cluster on Hetzner and followed this guide to install the cloud controller manager.  However, I have run into the following problems:

1. The controller manager originally started but has subsequently crashed and is reporting the following error:

```Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 2a01:4ff:ff00::add:2 2a01:4ff:ff00::add:1 185.12.64.2```

2. Core DNS also did not start after the initial kubeadm command to initialize K8S.  It is reporting the following errors in the log:

`[INFO] plugin/ready: Still waiting on: kubernetes
[ERROR] plugin/errors: 2 3619715707778063679.1294107178195040477. HINFO: read udp 10.0.1.3:42473->185.12.64.2:53: i/o timeout
[ERROR] plugin/errors: 2 3619715707778063679.1294107178195040477. HINFO: dial udp [2a01:4ff:ff00::add:1]:53: connect: network is unreachable
[ERROR] plugin/errors: 2 3619715707778063679.1294107178195040477. HINFO: read udp 10.0.1.3:53655->185.12.64.2:53: i/o timeout
[ERROR] plugin/errors: 2 3619715707778063679.1294107178195040477. HINFO: read udp 10.0.1.3:37248->185.12.64.2:53: i/o timeout
[ERROR] plugin/errors: 2 3619715707778063679.1294107178195040477. HINFO: dial udp [2a01:4ff:ff00::add:2]:53: connect: network is unreachable`

The pod logs also show this error which maybe related:

```0/1 nodes are available: 1 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.```

The only differences from following the guide are:

My private network on Hetzner uses the IP scheme 10.0.0.x so I specified this option to the kubeadm command

```--pod-network-cidr=10.0.0.0/16```

I used the latest version of flannel as the one in the documentation does not work with K8S 1.23.3

```kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml```

Any help would be greatly appreciated ;)

**Comment by dclayton77** [comment]
So after much reading with some trial and error, I have managed to get a cluster fully setup and working.  I have a fully functional load balancer and have LinkerD service mesh and Cert-Manager HTTPS certificates generating.  To help others (and I hope this ok to post), I have written a three part blog post demonstrating how to get everything working together.

https://dcse-ltd.co.uk/building-a-bare-metal-kubernetes-cluster-part-1-hetzner-cloud/

**Comment by MichaelVoelkel** [comment]
Erm, a whole blog post is not really a good direct answer to this question? Could you at least highlight which part solves this specific problem?
