### ISSUE TITLE
providerID should start with hcloud://

### ISSUE THREAD

**Issue by igorcoding** [hetznercloud/hcloud-cloud-controller-manager#28]
Hello!
I installed hcloud-cloud-controller-manager into the newly created cluster and after adding a second node see the following logs of the controller:

```
ERROR: logging before flag.Parse: E1012 18:04:19.550861       1 node_controller.go:161] providerID should start with hcloud://: XXXXXX1
ERROR: logging before flag.Parse: E1012 18:09:20.964303       1 node_controller.go:161] providerID should start with hcloud://: XXXXXX1
ERROR: logging before flag.Parse: E1012 18:14:21.780274       1 node_controller.go:161] providerID should start with hcloud://: XXXXXX1
```

where XXXXXX1 is indeed an id of my second node in the Hetzner Cloud.
And no extra labels are added automatically to this second node.

I don't quite understand the reasons of it but apparently this log comes from here - https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/da9620fd70d385dc39e5a884201b00b893d1c6c8/hcloud/util.go#L56
Maybe this is some sort of misconfiguration from my side? Should I add any extra annotations or labels to the node?

**Comment by LKaemmerling** [comment]
Are you sure, that you have started the kubelet with `--cloud-provider=external` ?

**Comment by igorcoding** [comment]
Before the first run of kubelet I forgot to include it in the parameters, but then restarted with this setting. Should the node be rejoined from scratch?

**Comment by LKaemmerling** [comment]
All kubelets need to have this flag, otherwise, this won't work.

**Comment by igorcoding** [comment]
It does have the `--cloud-provider=external` setting right now

**Comment by LKaemmerling** [comment]
And does it work? We have setup a bunch of new clusters today with this configuration and it worked.

**Comment by igorcoding** [comment]
As I said, for the first start of kubelet this param was missing but now it's in place and still getting errors. It's interesting that private ip of a node has been successfully displayed after adding the cloud-provider param but no other node's labels have been added and controller still spams with the mentioned error.
I'll try to rejoin the node to the cluster - maybe that will help.

**Comment by LKaemmerling** [comment]
The other values are only added when the node join.

**Comment by igorcoding** [comment]
So yes, resetting and rejoining the node fixes the problem. Guess not a big problem. Thank you
