### ISSUE TITLE
Make CCM Compatible with Cilium 1.11

### ISSUE THREAD

**Issue by Contentways** [hetznercloud/hcloud-cloud-controller-manager#280]
Update the Readme with actual Cilium 1.11 and make the ccm compatible with it.

**Comment by morremeyer** [comment]
@Contentways I’m planning to use Cilium for one of my clusters. Can you go please document the issues that need to be fixed in here?

**Comment by nazarkulyk** [comment]
Cilium 11.x just work well with current CCM
