### ISSUE TITLE
Load balancer with control plane nodes only?

### ISSUE THREAD

**Issue by tboerger** [hetznercloud/hcloud-cloud-controller-manager#282]
I got a small cluster where control plane nodes also act as worker nodes, the load balancer gets created, but it doesn't have any target? Can somebody give me a hint how the load balancer takes the control plane nodes as a target?

**Comment by gris-gris** [comment]
up

**Comment by tboerger** [comment]
For those who came here for a solution, just set this feature gate within your hcloud ccm deployment and it will work: `--feature-gates=LegacyNodeRoleBehavior=false`

**Comment by mysticaltech** [comment]
@tboerger This seems to have been removed in the latest CCM, as I get this error now:

```
Error: invalid argument "LegacyNodeRoleBehavior=false" for "--feature-gates" flag: unrecognized feature gate: LegacyNodeRoleBehavior
Usage:
  cloud-controller-manager [flags]
```

What is the new way of achieving the above?

**Comment by mysticaltech** [comment]
I would propose re-opening this issue, as it no longer works and is causing an issue with our project https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/311; any help in solving this would be appreciated!

**Comment by mysticaltech** [comment]
@tboerger, I feel that the [feature-gates](https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/) page holds the key to getting this to work with the new CCM; especially interesting seem the `ServiceNodeExclusion` feature gate.

It says:

`ServiceNodeExclusion: Enable the exclusion of nodes from load balancers created by a cloud provider. A node is eligible for exclusion if labelled with "node.kubernetes.io/exclude-from-external-load-balancers".`

From the above, I would deduce that with the new setup, the "master" / "control-plane" label is not looked at by the CCM to deal with LBs if the `ServiceNodeExclusion` is set to true. It will only exclude nodes if they have the "exclude-from-external-load-balancers" label.

What do you think? Now probably a good idea to test. I will do it as soon as I have some time for this.
