### ISSUE TITLE
LoadBalancer Source Ranges

### ISSUE THREAD

**Issue by dcardellino** [hetznercloud/hcloud-cloud-controller-manager#286]
Hello together,

Does Hetzner LoadBalancer provide or plans to provide to support an annotation like on AWS, to restrict the ip addresses that can access the loadbalancer service?
The AWS ELB annotations is this one: `service.beta.kubernetes.io/load-balancer-source-ranges` where you can specify CIDRs that are allowed to access the NLB.

Thanks in advance,

Dom

**Comment by hakman** [comment]
At the moment Hetzner firewall cannot be applied to load balancers, so this is not technically possible:
https://docs.hetzner.com/cloud/firewalls/faq/#can-firewalls-be-applied-to-my-hetzner-cloud-load-balancers

Even if not quite the same, you could use an ingress behind the load balancer to do something similar:
https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#whitelist-source-range

**Comment by sebastiangaiser** [comment]
@hakman do you have an example how your Helm values would look like for the nginx-ingress controller?
Especially for the required annotations for the load balancer.

**Comment by dcardellino** [comment]
Helped out with a HAProxy deployment where I filter ip addresses.
