### ISSUE TITLE
lb didn't create if certificate is already there

### ISSUE THREAD

**Issue by fmt-Println-MKO** [hetznercloud/hcloud-cloud-controller-manager#287]
I used the following config in my Kubernetes deployment 

```
    load-balancer.hetzner.cloud/name: "xyz"
    load-balancer.hetzner.cloud/location: "fsn1"
    load-balancer.hetzner.cloud/disable-private-ingress: "false"
    load-balancer.hetzner.cloud/protocol: "https"
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/certificate-type: "managed"
    load-balancer.hetzner.cloud/http-managed-certificate-name: "xyz-name"
    load-balancer.hetzner.cloud/http-managed-certificate-domains: "XYZ.DOMAIN"
    load-balancer.hetzner.cloud/health-check-protocol: "http"
    load-balancer.hetzner.cloud/health-check-http-path: "/"
```

during an initial `apply` if this deployment everything works fine. 
the certificate is created and assigned to LB.

if I delete these deployments. 
everything besides the certificate will be deleted. 

If I know want to apply the deployment again, the LB is not set up correctly. there is no target and no service.

so I deleted the certificate manually, and now run into the rate limits :( 

I think the script should check if the certificate already exists with the given name and just use it.

**Comment by elohmeier** [comment]
This issue can be worked around by adding a label to the certificate:
`hcloud-ccm/service-uid:<service-uid>`

You can get the service uid e.g. by using `kubectl get services myservice -o jsonpath='{.metadata.uid}'`.

It is then picked up by CCM and the certificate is configured correctly for the load balancer.
