### ISSUE TITLE
LoadBalancerClass

### ISSUE THREAD

**Issue by goarano** [hetznercloud/hcloud-cloud-controller-manager#288]
Hey guys

First of all, thanks a lot for your hard work, the CCM is really useful :)
I was wondering whether you heard about the new LoadBalancerClass feature (stable since 1.24)?
Supporting this field would enable users to run multiple LB providers at the same time, e.g. hcloud and metallb.

https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class

**Comment by Lykos153** [comment]
I need this, too. Please re-open

**Comment by andriuspl** [comment]
Yup, please re-open.
