### ISSUE TITLE
Disabling Hetzner load balancer

### ISSUE THREAD

**Issue by rmja** [hetznercloud/hcloud-cloud-controller-manager#289]
Hi,

I have been using metallb for load balancing for years on Hetzner Cloud, but after I have upgraded the controller manager which now has Hetzner Load Balancer support, it seems as if I cannot create any new LoadBalancer services using metallb.
I now get the following error when creating a LB service:
```
Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set
```

I cannot use Hetzner LB yet as it still lacks udp support which I need.

How do I prevent the Hetzner Load Balancer to take over LB service creation and still use the load balancer configured on the cluster? I have other LoadBalancer services using metallb working on the cluster that were created before upgrading the controller manager, and they keep working just fine.

**Comment by hakman** [comment]
@rmja This may be similar or a duplicate of https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/288.
