### ISSUE TITLE
Release note for v1.5.0 seems wrong

### ISSUE THREAD

**Issue by invidian** [hetznercloud/hcloud-cloud-controller-manager#29]
It says:
>Add support for Kubernetes 1.6.x

While support for Kubernetes 1.16.x been added, according to https://github.com/hetznercloud/hcloud-cloud-controller-manager/commit/4caf852aa92aa628e2e8d0afabf634c3f28b91e5 :)

**Comment by LKaemmerling** [comment]
Fixed, thank you :)
