### ISSUE TITLE
Supporting primary IPs

### ISSUE THREAD

**Issue by hnaderi** [hetznercloud/hcloud-cloud-controller-manager#292]
I was wondering if supporting new [primary IPs](https://docs.hetzner.com/cloud/servers/primary-ips/overview) would be in the scope of this project?  
I was thinking of some kind of annotation like the one used for load balancer, that when used on Node or machine objects, creates a new server with the specified primary IP.  
I don't have any idea of its complexity or whether or not this would be the best way to do it, please let me know of a better way or an existing implementation.

**Comment by LKaemmerling** [comment]
Hey @hnaderi,

the cloud controller manager is not in charge of creating servers, this would be part of the https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler. However, we will update the Cloud Controller Manager to do not break when using Flexible Networks.
