### ISSUE TITLE
Add prometheus support

### ISSUE THREAD

**Issue by LKaemmerling** [hetznercloud/hcloud-cloud-controller-manager#31]
We want to expose the Go metrics for Prometheus.

You can have a look at https://github.com/hetznercloud/csi-driver/pull/67, where the metrics are implemented in a similar way.

**Comment by LKaemmerling** [comment]
We have already reserved a port for this: 9465 (https://github.com/prometheus/prometheus/wiki/Default-port-allocations)

**Comment by cbeneke** [comment]
Was this discarded or just deprioritized/forgotten about? :)

**Comment by LKaemmerling** [comment]
It is still on our todo list :) I just missed to label this issue.

**Comment by LKaemmerling** [comment]
I think atm it won't make sense to expose metrics for the CCM, as the CCM itself is really small. We might consider it in the future.
