### ISSUE TITLE
[BUG] Healthcheck ports are mixed up after a new target is added to the LB

### ISSUE THREAD

**Issue by pmdroid** [hetznercloud/hcloud-cloud-controller-manager#323]
When using an LB with HTTP and HTTPS the ports are switched around when a new target is added to the LB. When the LB is initially created the result is expected, both services are registered with the correct ports and health checks. But when a new target is added the second health check will be overwritten with the port of the first health check. The problem happens [here](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/internal/annotation/load_balancer.go#L249) when the LB as created and the annotations are added to the service. The problem is that then the port of the first service is assigned to the service annotation as "load-balancer.hetzner.cloud/health-check-port" when then the second health check is updated the port is used from the annotation.

I have fixed the issues for me temporarily with this [commit](https://github.com/pmdroid/hcloud-cloud-controller-manager/commit/1c9fc4e97cf66e7f46cfe54d9d0dedff1cdc2797)

I think only needed annotations should be added to the service like lbid, uid .... but annotations that are not existing in the service like "load-balancer.hetzner.cloud/health-check-port" should not be added by default back to the service. When I understood the code correctly these added annotations are only used within the cloud controller anyways. When I removed then the controller still worked as expected. Why are they added and not saved back to the k8s service?

**Comment by apricote** [comment]
I have a hard time understanding your setup.

How is the loadbalancer and the services initially setup? Can you provide a manifest of the service that you are using for this?

As far as I understood, the hetzner-cloud-controller-manager only supports one health check per (kubernetes) `Service` that is applied to all (hcloud) `Services` in the loadbalancer.
