### ISSUE TITLE
[QUESTION] Where does the route to the private network come from?

### ISSUE THREAD

**Issue by ibot3** [hetznercloud/hcloud-cloud-controller-manager#329]
I am currently thinking about switching to the CCM networking instead of an additional overlay network (currently with calico).

The network setup:

- `eth0` with a public IP and a default route pointing to it.
- `enp7s0` as private network with all nodes (addresses from `10.1.0.0/24`)
- `10.3.0.0/16` as range for the `/24` pod networks

I see that the CCM creates the routes for the pod networks with the private network IPs as gateway:

![https://i.imgur.com/opNcL9E.png](https://i.imgur.com/opNcL9E.png)

However, the only route that matches the other pod networks on each node is the default route to `eth0`. So for this whole setup to work I need to add a static route `ip r add 10.3.0.0/16 via 10.1.0.1`.

But this somehow doesn't feel right but I could not find how others do it.. Should the CNI Plugin add this route somehow? Or should the CCM do this?

**Comment by apricote** [comment]
Hi @ibot3,

sorry for taking so long to answer.

The answer depends on one thing, is your pod CIDR within the network CIDR?

- If *yes*, the [automatically created networking route](https://docs.hetzner.com/cloud/networks/server-configuration/) sends all requests through the router (first IP in your subnet, e.g. `10.1.0.1` for you).
- If *no*, then you need to manually setup the route on your servers. See [What is special about route destinations that are not part of my network IP range?](https://docs.hetzner.com/cloud/networks/faq#what-is-special-about-route-destinations-that-are-not-part-of-my-network-ip-range") in our networks docs.

Once the request reaches the router, it redirects that traffic according to the `route` in our api, as created by the CCM.

You can check out the docs on [setting up the hccm with native networking](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/deploy_with_networks.md#deployment-with-networks-support).

I am going to close this issue, if you have any further questions, please feel free to post them here or to open a new issue.
