### ISSUE TITLE
Internal and External IP switched

### ISSUE THREAD

**Issue by zmbcgn** [hetznercloud/hcloud-cloud-controller-manager#337]
Hi there. 

I fail to get my IPs right on the new build k8s cluster with Hetzner cloud. I followed more or less this guide (https://jmrobles.medium.com/how-to-create-a-kubernetes-cluster-with-rancher-on-hetzner-3b2f7f0c037a) and tried to use the latest versions, maybe that were my problem began.

My setup is:
1 CX21 for Rancher
1 CX21 Master
1 CX31 Worker

The cluster's internal network is NOT 10.244.0.0/16, it is 10.42.0.0/16. I guess that is something the hetzner cloud driver of Rancher did.

I have installed the hcloud cloud controller manager and flannel (version 0.9.1). I also tried the flannel version 0.20.2. But I was unsure because the 0.9.1 is from coreos and the newer is from flannel.io. Nevertheless, it did not make any difference.

My current situation is like this:
```
./kubectl get nodes -o wide
NAME       STATUS   ROLES               AGE   VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
master-1   Ready    controlplane,etcd   10h   v1.24.8   5.75.<ommited>   <none>        Ubuntu 20.04.5 LTS   5.4.0-137-generic   docker://20.10.22
worker-1   Ready    worker              10h   v1.24.8   23.88.<ommited>    <none>        Ubuntu 20.04.5 LTS   5.4.0-137-generic   docker://20.10.22
```
Screenshot from Rancher:
![grafik](https://user-images.githubusercontent.com/25174550/212897633-4fa02784-d410-464e-8ca5-c59b232a8eed.png)

As far as I can see, the flannel pod and the hcloud ccm pod are running without any issues. So I don't know were to search, and I don't know if it is a flannel issue or hcloud ccm.

If it is relevant: Rancher Version is 2.7.0

Thanks for helping.

zmbcgn

**Comment by apricote** [comment]
Hi @zmbcgn,

can you upload the output of `kubectl get node -o yaml`? If you do not want to post this publicly, you can also send to me via email at `julian.toelle <at> hetzner-cloud.de`.

Also, how did you install the `hcloud-cloud-controller-manager` and what version are you using? The tutorial you linked did not include the installation of the `hcloud-cloud-controller-manager`.

**Comment by zmbcgn** [comment]
Hi, 

sorry, I am afraid I can do that, because after several hours/days of troubleshooting and trying with different guides:

like
https://acsec.pro/creating-a-kubernetes-cluster-on-hetzner-cloud-with-hetzner-ccm-rancher-traefik-and-cloudflare

or the "official":
https://community.hetzner.com/tutorials/install-kubernetes-cluster

I gave up, as it was to much hassle for me for a "hobby" project.  At least with the guide from "acsec" I managed to set up a cluster with the external and internal IP set right. Then I had issues to setup the Traefik and LoadBalancer / Floating IPs right etc.

In terms of this issue: We can safely close this, as i guess it was just an implementation issue. 

Sidenote:
Maybe you can update the community guide on the Hetzner site to a current state. In this guide there is still mentioned that the Hetzner CCM is not able to handle Loadbalancers and the rest of the guide (based on Ubuntu 18.04) is also out-of-date.

thanks anyway!

**Comment by apricote** [comment]
> In terms of this issue: We can safely close this, as i guess it was just an implementation issue.

Will do so!

> Sidenote:
> Maybe you can update the community guide on the Hetzner site to a current state. In this guide there is still mentioned that the Hetzner CCM is not able to handle Loadbalancers and the rest of the guide (based on Ubuntu 18.04) is also out-of-date.

If you dont mind, you can open an issue on the repo that contains the guide: https://github.com/hetzneronline/community-content
