### ISSUE TITLE
Support LoadBalancerClass in Services

### ISSUE THREAD

**Issue by sebastiangaiser** [hetznercloud/hcloud-cloud-controller-manager#338]
In order to have the possibility to use different LoadBalancers, it would be awesome to support [this](https://kubernetes.io/docs/concepts/services-networking/service/#load-balancer-class).

**Comment by apricote** [comment]
It looks like this is implemented in `k8s.io/cloud-provider`: https://github.com/kubernetes/cloud-provider/blob/4787df198facafb366cc1ef7e2bb4d9fec82f856/controllers/service/controller.go#L793-L796

Our implementation is only called for `Services` that have no `LoadBalancerClass` specified, as we provide the "default" implementation.
