### ISSUE TITLE
network configuration using rancher

### ISSUE THREAD

**Issue by kozy** [hetznercloud/hcloud-cloud-controller-manager#34]
Hi, and thanks for this great controller, it seems to work well setting the nodes metadata, but I can not seem to get it to work with the network.

I use flannel in a fresh installation of rancher. Everything is default.  It seems after I apply the deployment part of the networking is wrong and dns is unreachable. When logging in to the node the ip of kube dns is indeed unreachable.

- Created the network according to the docs
- Set the secret for network and token using --from-literal
- I changed `--cluster-cidr=10.42.0.0/16`, because of the following rancher defaults.
- Applied the deployment to the cluster

Direclty the nodes output event 'RouteController failed to create a route'

```0s          Warning   FailedToCreateRoute       node/master1   Could not create route fe8eb8f5-8070-4632-995d-811545595a54 10.42.0.0/24 for node master1 after 228.108063ms: server master1 not found```

The nodes seem to properly get the metadata however the network is not assigned to any of the nodes. 

These are the last lines of the log of the pod

```
ERROR: logging before flag.Parse: I1216 00:09:21.374900       1 route_controller.go:176] Creating route for node worker1 10.42.1.0/24 with hint 30560909-ab51-4f84-a3a6-aa46fed1a46b, throttled 755ns
ERROR: logging before flag.Parse: I1216 00:09:21.374984       1 route_controller.go:176] Creating route for node master1 10.42.0.0/24 with hint fe8eb8f5-8070-4632-995d-811545595a54, throttled 1.92µs
ERROR: logging before flag.Parse: E1216 00:09:21.574934       1 route_controller.go:199] Could not create route 30560909-ab51-4f84-a3a6-aa46fed1a46b 10.42.1.0/24 for node worker1: server worker1 not found
ERROR: logging before flag.Parse: I1216 00:09:21.575333       1 event.go:221] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"worker1", UID:"worker1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedToCreateRoute' Could not create route 30560909-ab51-4f84-a3a6-aa46fed1a46b 10.42.1.0/24 for node worker1 after 200.008981ms: server worker1 not found
ERROR: logging before flag.Parse: E1216 00:09:21.596687       1 route_controller.go:199] Could not create route fe8eb8f5-8070-4632-995d-811545595a54 10.42.0.0/24 for node master1: server master1 not found
ERROR: logging before flag.Parse: I1216 00:09:21.596751       1 event.go:221] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"master1", UID:"master1", APIVersion:"", ResourceVersion:"", FieldPath:""}): type: 'Warning' reason: 'FailedToCreateRoute' Could not create route fe8eb8f5-8070-4632-995d-811545595a54 10.42.0.0/24 for node master1 after 221.703601ms: server master1 not found
```

And here are some relevant rancher setting and defaults

```

  network:
    options:
      flannel_backend_type: vxlan
    plugin: flannel
# 
#    services:
#      kube-api:
#        service_cluster_ip_range: 10.43.0.0/16
#      kube-controller:
#        cluster_cidr: 10.42.0.0/16
#        service_cluster_ip_range: 10.43.0.0/16
#      kubelet:
#        cluster_domain: cluster.local
#        cluster_dns_server: 10.43.0.10
```

route -n

```
0.0.0.0         172.31.1.1      0.0.0.0         UG    0      0        0 eth0
10.42.0.0       10.42.0.0       255.255.255.0   UG    0      0        0 flannel.1
10.42.1.0       0.0.0.0         255.255.255.0   U     0      0        0 cni0
172.17.0.0      0.0.0.0         255.255.0.0     U     0      0        0 docker0
172.31.1.1      0.0.0.0         255.255.255.255 UH    0      0        0 eth0
```
Not sure how to debug this. I think it is something simple with the network setting. Any ideas? Thanks!

**Comment by driehle** [comment]
I am experiencing a similar issue. Have you been able to set up the cluster automatically (by Rancher) or are you setting up the cluster manually and adding hcloud-cloud-controller-manager manually as well?

**Comment by kozy** [comment]
I installed the cluster automatically using the [hetzner ui driver](https://github.com/mxschmitt/ui-driver-hetzner)

**Comment by driehle** [comment]
Did you add additonal config beside the one below? Because with cloud_provider set to external, my networking doesn't work either. Not using Rancher, but following the instructions of hcloud-cloud-controller works however.

```
rancher_kubernetes_engine_config:
  cloud_provider:
    name: external
  network:
    options:
      flannel_backend_type: vxlan
    plugin: flannel
```

**Comment by kozy** [comment]
I set the cloud-provider using extra-ops for the service because of a bug in rancher. But no, no other configuration other than that

**Comment by kozy** [comment]
Finally took the time to take a closer look. It appeared controller manager expected the network already attached to the servers. That was all
