### ISSUE TITLE
Annotations to reference an existing loadbalancer

### ISSUE THREAD

**Issue by gthieleb** [hetznercloud/hcloud-cloud-controller-manager#351]
As it seems not explicitly mentioned in the docs I would like to know what are the required annotations to reference an existing loadbalancer (e.g. created outside with terraform).

Is it suffice to reference the location and the name?

```
load-balancer.hetzner.cloud/location: nbg11
load-balancer.hetzner.cloud/name: myname
```

**Comment by apricote** [comment]
I added this to the docs: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/load_balancers.md#reference-existing-load-balancers
