### ISSUE TITLE
Target nodes in a specific region only

### ISSUE THREAD

**Issue by renchap** [hetznercloud/hcloud-cloud-controller-manager#373]
We have a multi region cluster (HEL and FSN), as we have apps deployed in both of those (but each app is contained into one region only).

We deployed 2 `ingress-nginx` instances, one in each region, using node selectors so it only runs in its own region. Then each app configures its `IngressClassName` to be handled by the regional nginx instances.

This created 2 Hetzner load-balancers, one in each region, but targets for those loadbalancers contain every node in the cluster. It would be really useful to be able to add an annotation to restrict targets to the correct region, as we currently can have trafic hitting our `eu-central` loadbalancer, then the data is sent to a node in HEL1, and it is routed back to FSN1 as the nginx pods are only running there.

**Comment by apricote** [comment]
Hey @renchap, this is not supported right now, there is only the possibility to exclude a node from all LoadBalancers using label [`node.kubernetes.io/exclude-from-external-load-balancer`](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-kubernetes-io-exclude-from-external-load-balancer).

**Comment by renchap** [comment]
Yes, I am using this for our controlplane nodes, but it would prevent any nginx instances to be scheduled here, where I want some of them to be.

Would you be open to a PR implementing this? Do you have a preference in the way it is done (label name…)

**Comment by apricote** [comment]
We are open to a PR that implements this. I would prefer the following implementation. Please comment if you think something else is is more appropriate :)

#### Annotation

We add a new annotation:

```go
LBNodeSelector Name = "load-balancer.hetzner.cloud/node-selector"
```

This annotation contains a label selector string matching the [string based format](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#list-and-watch-filtering) used in `kubectl`.

#### Evaluation

The label selector can be parsed and evaluated using

- [`labels.Parse()`](https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Parse) and
- [`labels.Selector.Matches()`](https://pkg.go.dev/k8s.io/apimachinery/pkg/labels#Selector)

This happens in `github.com/hetznercloud/hcloud-cloud-controller-manager/hcloud#EnsureLoadBalancer` before the nodes are passed to `hcops`/`lbops`.
