### ISSUE TITLE
Instances(V1) interface access is not cached, API rate limited

### ISSUE THREAD

**Issue by hifi** [hetznercloud/hcloud-cloud-controller-manager#384]
We run a fairly large cluster on Hetzner. Initially based on errors I assumed we had hit #330 but it wasn't as much API access than I expected.

Debugging with `HCLOUD_DEBUG` enabled I saw that about each five minutes `/v1/servers/{id}` was being called by the controller twice for each node. This became a problem when the node count exceeded the default API regeneration rate (1 req/s) at around 150 nodes.

I think it would be reasonable to use and refresh a shared `hcops.AllServersCache` as it uses the paginated call to build a full cache and it will drop the number of API calls down significantly without functionality loss or making the cache time longer.

**Comment by hifi** [comment]
I hacked around with `hcops.AllServersCache` here: https://github.com/beeper/hcloud-cloud-controller-manager/commit/733bcf9e3e2745ba85374894915bbefb90649a60

Based on the results this cut down the requests from ~200 on startup and constantly draining because of #330 to 4 per minute max when the cache expires.

Because the paginated API for servers isn't transactional and would likely give incorrect results if servers are being added/removed during pagination a good implementation that wouldn't drain the API rate limit nor cause unnecessary cache misses would be better as a pull-through cache that is initialized from the full list on startup.

So if the server cache is seeded with the paginated data but refreshed based on access (and per-instance expiry time) it would prevent the API flood on startup and also always be up-to-date. Because of #330 it would also need to have an increasing backoff time to fetch a missing server from the API to prevent it from draining API rate limit by making the backoff long enough that even a large amount of out-of-cloud servers wouldn't cause that.

What do you think of this approach and this issue in general?

**Comment by apricote** [comment]
Hey @hifi,

right now you should be able to set [`--node-status-update-frequency`](https://github.com/kubernetes/cloud-provider/blob/4162b590014735c81ac6db5e3fbf7edaae3d4706/options/options.go#L137) to reduce the frequency of node status updates. This defaults to the [5 minutes](https://github.com/kubernetes/cloud-provider/blob/4162b590014735c81ac6db5e3fbf7edaae3d4706/config/v1alpha1/defaults.go#L37) you mentioned.

Before we add any complexity to the existing interface, I would prefer to migrate our usage from `Instances` to [`InstancesV2`](https://github.com/kubernetes/cloud-provider/blob/4162b590014735c81ac6db5e3fbf7edaae3d4706/cloud.go#L52-L56):

```go
	// InstancesV2 is an implementation for instances and should only be implemented by external cloud providers.
	// Implementing InstancesV2 is behaviorally identical to Instances but is optimized to significantly reduce
	// API calls to the cloud provider when registering and syncing nodes. Implementation of this interface will
	// disable calls to the Zones interface. Also returns true if the interface is supported, false otherwise.
	InstancesV2() (InstancesV2, bool)
```

I will have a look tomorrow with @samcday to see how quickly we can refactor this.

**Comment by hifi** [comment]
Thank you for looking into it!

Whatever the approach is it should be able to scale to massive clusters with many hundreds of nodes and prevent trashing the API when bare metal nodes are part of the cluster.

The cache hacks I placed in our patch will as-is allow that already albeit slowing down registering new nodes with the forced cache time which isn't ideal.

**Comment by apricote** [comment]
We migrated to `InstancesV2` in #385, this should improve the number of API calls made for new nodes by a factor of ~4 (improvement as described in kubernetes/kubernetes#90652)

Additionally we found one unecessary API call o that was being made on every node status update when the private network support was enabled. This is being removed in #386.

**Comment by hifi** [comment]
Thank you for the swift fix! I can't verify it from current main yet but that indeed sounds like it will help. Will update this ticket with findings once we have it running.

**Comment by samcday** [comment]
Hello @hifi - as mentioned already by @apricote hccm `1.14.1` is out with an InstancesV2 implementation. As such, the InstanceV1 API is [completely removed](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/hcloud/cloud.go#L180).

We've also identified more room for improvement with API usage in #395.

I'm going to close this ticket now. Please feel free to reach out with any further issues!
