### ISSUE TITLE
deployment files missing

### ISSUE THREAD

**Issue by kossmac** [hetznercloud/hcloud-cloud-controller-manager#393]
Hi,

the deployment files(eg. https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.14.0/ccm-networks.yaml) referenced in the readme for the 1.14.0 release are missing.

**Comment by apricote** [comment]
Hey @kossmac,

we are aware of issues with the `v1.14.0` release and are about to release a fix for it: #392

**Comment by apricote** [comment]
The release `v1.14.1` is now published and includes the files.
