### ISSUE TITLE
Issues if lookupServer() returns nil server

### ISSUE THREAD

**Issue by janiskemper** [hetznercloud/hcloud-cloud-controller-manager#398]
As far as I understand, the lookupServer function can return a nil server. You also indicate that in the comment above (even though it seems as if the comment is missing its last part https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/hcloud/instances.go#L49).

However, are the functions InstanceShutdown and InstanceMetadata really able to handle a nil server? I think they would panic.

I guess that an error should be returned if the server is not found, i.e. nil, and the InstanceShutdown or InstanceMetadata functions are called. What do you think?

**Comment by samcday** [comment]
I think this is fine, cloud-provider [can indeed handle nil results](https://github.com/kubernetes/cloud-provider/blob/cb9829733364b7270f1bd64276da2fe9141ceaf7/controllers/node/node_controller.go#L440) from these APIs.

If you find a specific issue that is affecting you though, then of course please feel free to open another ticket!

**Comment by janiskemper** [comment]
Maybe I'm blind, but if the server object returned by lookupServer is nil, wouldn't you get a panic due to nil pointer dereference here? https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/hcloud/instances.go#L107

**Comment by apricote** [comment]
This is an actual issue as far as I can see because `lookupServer` is an internal API and we do not properly handle the `nil` server here for example: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/109e4b1ccd007c57c40bdf87b8f1193729c2b240/hcloud/instances.go#L93

**Comment by apricote** [comment]
Thanks for the report @janiskemper, will be fixed in the next patch release.

**Comment by janiskemper** [comment]
Nice! No problem :)
