### ISSUE TITLE
Add server labels as node labels

### ISSUE THREAD

**Issue by CuBiC3D** [hetznercloud/hcloud-cloud-controller-manager#41]
It would be quite nice to have server labels from Hetzner to be set as node labels by the controller.
Would be then possible to provision servers by e.g. Terraform as workers with cloud-init and cluster join parameters and have labels available for scheduling selection after node initialization.

**Comment by CuBiC3D** [comment]
Still useful? =/

**Comment by LKaemmerling** [comment]
Hey, 

actually we have a few problems with this, as we don't have access to the node labels (or annotations) directly, so we would need to query the k8s API for this. We will look further into this in the future. 

@fhofherr could you please look into this?

**Comment by LKaemmerling** [comment]
@CuBiC3D i did a bit of research here. Using the k8s labels for this is quite a bit annoying i would favor using annotations here (so we fill annotations with the labels). Do you think a "2 way sync" (Labels  from k8s into the hcloud) would also help?

**Comment by CuBiC3D** [comment]
@LKaemmerling annotations are non-identifiable attributes in the k8s world, this would not allow to use them in probably most useful situations like with `nodeSelector` to create pod to node preferences.

2-way-sync would probably be beneficial for in-cluster apps running automation tasks and probably relabel or remove.

**Comment by LKaemmerling** [comment]
We decided to not implement it, because it doesn't fit with the cloud controller spec from k8s.
