### ISSUE TITLE
openshift cluster - private network

### ISSUE THREAD

**Issue by itmwiw** [hetznercloud/hcloud-cloud-controller-manager#422]
Hello,
I installed openshift on hetzner, using a private cloud. That means all my nodes only have private ip adresses. Now I want to use hccm to dynamically provide loadbalancers. 
I installed hccm via the helm chart with networking.enabled=false as I use OpenshiftSDN cni.
When I try to create a loadbalancer service I get the following error message: 
```bash
Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: use private ip: missing network id
```
To create the service I used the following annotations:
```yaml
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/use-private-ip: "true"
```
Can you help me with this? Is it possible to dynamically connect the loadbalncer to my private hcloud network without depending on it for the CNI part (Use it only for the nodes not the pods)? 
Regards,
Tarik

Edit: Apart from the private network question, I figured out I did add --cloud-provider=external AFTER the cluster was up and running. I guess this should be done at day-1, before the installation completes. Hence my second question, is hccm compatible with Openshift?

**Comment by samcday** [comment]
Perhaps you're missing some [configuration steps](https://github.com/hetznercloud/hcloud-cloud-controller-manager#networks-support) for private networking support? That error indicates no `HCLOUD_NETWORK` has been set.

> Is it possible to dynamically connect the loadbalncer to my private hcloud network without depending on it for the CNI part (Use it only for the nodes not the pods)?

This project does not perform any CNI duties for you. You must still install and configure your own. If you want the load balancer to route traffic to your pod through the private network, then the private network requires routes for hcloud Node PodCIDRs. hccm will create those routes for you, when network support is enabled.

> Hence my second question, is hccm compatible with Openshift?

I'm not aware of any specific incompatibilities. Though there's no automated testing to verify Openshift installations.

**Comment by samcday** [comment]
> I figured out I did add --cloud-provider=external AFTER the cluster was up and running

I think this should be okay. You can verify by checking the `spec.providerID` of each hcloud node in your cluster. It should begin with `hcloud://`. This indicates hccm reconciled the Node and did cloud-y things with it.

**Comment by itmwiw** [comment]
Hello, Thanks for the reply.
> Perhaps you're missing some [configuration steps](https://github.com/hetznercloud/hcloud-cloud-controller-manager#networks-support) for private networking support? That error indicates no `HCLOUD_NETWORK` has been set.
> 
> > Is it possible to dynamically connect the loadbalncer to my private hcloud network without depending on it for the CNI part (Use it only for the nodes not the pods)?
> 
> This project does not perform any CNI duties for you. You must still install and configure your own. If you want the load balancer to route traffic to your pod through the private network, then the private network requires routes for hcloud Node PodCIDRs. hccm will create those routes for you, when network support is enabled.
> 
> > Hence my second question, is hccm compatible with Openshift?
> 
> I'm not aware of any specific incompatibilities. Though there's no automated testing to verify Openshift installations.

Ok for the private network, I'll try it again. That leaves only the second point.
> > I figured out I did add --cloud-provider=external AFTER the cluster was up and running
> 
> I think this should be okay. You can verify by checking the `spec.providerID` of each hcloud node in your cluster. It should begin with `hcloud://`. This indicates hccm reconciled the Node and did cloud-y things with it.

No, It didn't add the spec.providerID section. Actually I was getting the same error message as in this issue: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/80
That is why I assumed I have to add the --cloud-provider=external beforehand. Is it not the case?
Regards,
Tarik

**Comment by samcday** [comment]
Hey Tarik,

What the `--cloud-provider=external` to kubelet does is tell it to skip any in-tree cloud initialization, and wait for an external process to handle initializing a new cloud Node.

The signal that this initialization is required is a special Node Taint. Could you try running this command against one of your hcloud Nodes that does not yet a valid `spec.provider=hcloud://...` set:

```
kubectl taint node <your node> node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
```

**Comment by samcday** [comment]
Yay :tada: since both the original issues you detailed seem to now be addressed, and as previously mentioned there's no known incompatibilities with Openshift, I'ma close this ticket now.

Feel free to re-open or open a new issue if you run into anything else. But of course I hope you don't, and that it's all smooth sailing for you from here :boat:

**Comment by samcday** [comment]
Oh by the way, I nerd-sniped myself a little and snooped on the openshift/sdn README.

Something for you to be aware of: I'm not sure how that CNI wants to handle IPAM, but hccm is only compatible with Kubernetes IPAM. That is, if you don't see some digits in `.spec.podCIDR`, then it's unlikely that LBs are going to reach your workloads through the private network.

**Comment by itmwiw** [comment]
I'm still having issue with private network. Here's the error message: 
```Bash
Cloud provider could not be initialized: could not init cloud provider "hcloud": hcloud/newCloud: checking if server is in Network not possible: serverIsAttachedToNetwork: Get "http://169.254.169.254/hetzner/v1/metadata/private-networks": dial tcp 169.254.169.254:80: connect: connection refused
```
Any workaround?

**Comment by itmwiw** [comment]
It was a misconfiguration from my side.
Now the LB has been created, the nodes added as targets and the ports->nodeports added to the load balancer's services.
I'll do a connectivity test to check everything is fine.

**Comment by samcday** [comment]
>  Thanks for the help @samcday !

You're welcome :)

> Oh by the way, I nerd-sniped myself a little and snooped on the openshift/sdn README.
> 
> Something for you to be aware of: I'm not sure how that CNI wants to handle IPAM, but hccm is only compatible with Kubernetes IPAM. That is, if you don't see some digits in `.spec.podCIDR` of your hcloud Nodes, then I think it unlikely that LBs are going to reach your workloads through the private network.

Turns out, this is untrue. When hccm configures a LB to use the private network, it's still sending traffic to the allocated NodePort of the Service, just on the private address instead of the public one. /cc @apricote  did I get it right this time? :sweat_smile:

**Comment by TheNonexistent** [comment]
@itmwiw Can you explain how you ended up fixing this issue?
```
Cloud provider could not be initialized: could not init cloud provider "hcloud": hcloud/newCloud: checking if server is in Network not possible: serverIsAttachedToNetwork: Get "http://169.254.169.254/hetzner/v1/metadata/private-networks": dial tcp 169.254.169.254:80: connect: connection refused
```
I'm facing the same problem.

**Comment by apricote** [comment]
This is only a sanity check to make sure users dont accidentally have the wrong config. You can disable it by setting the environment variable `HCLOUD_NETWORK_DISABLE_ATTACHED_CHECK=true`.
