### ISSUE TITLE
Merge our baremetal ccm into hcloud ccm?

### ISSUE THREAD

**Issue by guettli** [hetznercloud/hcloud-cloud-controller-manager#438]
I guess most people know that we provide a ccm based upon hetznercloud/hcloud-cloud-controller-manager which supports bare metal hosts.

https://github.com/syself/hetzner-cloud-controller-manager

Maintaining this enhanced fork is extra work, and we think that a joined effort would reduce work and it would reduce confusion for new users.

Our (Syself) ccm is your ccm with support for bare metal (we don't alter the hcloud handling).

I know that you are two different business units (hetznercloud vs hetzner), but wouldn't it be better have one ccm for both use cases?

If you agree, then we could create a PR to merge our changes into your ccm.

**Comment by guettli** [comment]
@apricote what do you think about merging our changes to hcloud ccm?

**Comment by guettli** [comment]
Since Hetzner seems to have no interest in joining hetzner baremetal support to the hcloud ccm, we (Syself) invite everybody to use our ccm. It supports both (hcloud and hetzner BM): https://github.com/syself/hetzner-cloud-controller-manager

**Comment by apricote** [comment]
Sorry for staying private/silent on this for so long. We do have plans to incorporate the Syself changes / Hetzner Robot support eventually, and are currently talking to the Robot team to make plans for this. I can not share an ETA on when this will be made available.

**Comment by schmidp** [comment]
@guettli do you plan another rebase of your controller in the meantime?
I am afraid of switching and falling behind on bugfixes.

Also currently the run:tests badge fails and makes me anxious about the state of the fork.

**Comment by guettli** [comment]
@schmidp thank you for asking. I started a discussion internaly at Syself. I guess we will merge the up to now 37 commits of the upstream CCM into our version during the next weeks.

**Comment by apricote** [comment]
Hey all! I have created #523 to track the merge. Please follow that issue if you are interested in updates.
