### ISSUE TITLE
Hetzner Load Balancer sporadically losing targets

### ISSUE THREAD

**Issue by dcardellino** [hetznercloud/hcloud-cloud-controller-manager#452]
Hello together,

We currently having some troubles with the Hetzner Load Balancer on Kubernetes managed through hcloud-ccm.

We are exposing some services through nginx-ingress to the web. At some times in a day this load balancer on hetzner cloud is loosing almost every target and so all our services going down.

Did somebody experience some similar issues?

This is really bad because our customers can't connect to our services.

**Comment by apricote** [comment]
This might be related to current ongoing maintenance work: https://status.hetzner.com/incident/64988819-c36f-4556-9f5f-5496e02983e1

It would be best if you open a support ticket: https://console.hetzner.cloud/support

**Comment by apricote** [comment]
I am not aware of any issues with load balancers in Helsinki. Are the hccm logs showing anything regarding adding and removing servers?

If you send me the load balancer ID I can take a look, but in general I recommend going through the support to get help with individual issues, as we have more tools (and people) available there to help you.

**Comment by dcardellino** [comment]
@apricote This is the load balancer id `1154597` The errors occured between 08:25 - 08:35 (German Time)

**Comment by apricote** [comment]
I see a single target being removed at 8:26:24 and a single target being added at 8:30:38. In addition to that there were many calls to the `update_service` action from 8:26 - 8:33 and multiple times again after that.

Could you enable debug logs for the HCCM by setting the environment variable `HCLOUD_DEBUG=true` and then send me the full logs to `julian.toelle <at> hetzner-cloud.de`?

**Comment by dcardellino** [comment]
@apricote I will update you via mail when the error happens again!
