### ISSUE TITLE
Feature: Better Floating IP support

### ISSUE THREAD

**Issue by Shakahs** [hetznercloud/hcloud-cloud-controller-manager#468]
Feature Request:

- HCCM should be aware of floating IP assignment changes and add/remove floating IPs on the node's network interface when necessary.
- HCCM should apply a Label to Nodes with a floating IP so workloads can be targeted to that IP, something like `ccm.hetzner.cloud/floatingipv4=1.2.3.4`.
- HCCM should also add the Floating IP to the node's Addresses->ExternalIP list for accuracy.

Floating IPs are important operational information. Similar information such as instance type, location, and private IP is already made available via Labels and Annotations:
```
Labels:
beta.kubernetes.io/instance-type=cpx21
csi.hetzner.cloud/location=ash
topology.kubernetes.io/zone=ash-dc1
...
Annotations:
alpha.kubernetes.io/provided-node-ip: 10.0.0.5
...
```

My use case:
I use an API that requires me to send requests from a single static IP address.
I can ensure my Pods send requests from the correct IP with Cilium [Egress Gateway](https://docs.cilium.io/en/v1.13/network/egress-gateway/), but for Egress Gateway to work the node with the floating IP needs to be labeled, and needs to be configured to use the IP.

**Comment by samcday** [comment]
You might be interested in [hcloud-fip-k8s](https://github.com/samcday/hcloud-fip-k8s/). I originally wrote it precisely for the use case you described (Cilium Egress Gateway usage). Documentation is a little lacking (like all good side projects, and 100% of all projects I've ever authored). Feel free to ping me if you're trying to use it and have questions, though.

**Comment by Shakahs** [comment]
@samcday thanks for the tip, and for writing a whole controller. I will use that for now.

This feature request is still valid, Floating IPs are very important and should be natively supported by the Hetzner CCM, or perhaps a Hetzner CNI.

**Comment by samcday** [comment]
> Floating IPs are very important and should be natively supported by the Hetzner CCM

100% agree. If you successfully put that controller to use, perhaps you could mention that here. That would strengthen the case for upstreaming it (or something like it) into the official CCM ;)

**Comment by EternalDeiwos** [comment]
Pity this became stale. Any chance it can be reopened?

**Comment by apricote** [comment]
> HCCM should be aware of floating IP assignment changes and add/remove floating IPs on the node's network interface when necessary.

This will probably not happen in this project, as it would require us to run something on the node to add the IP addresses there.

> Labels/Annotations/Status

This might be possible, but any updates made through the Hetzner Cloud API will be reconciled slowly into the Kubernetes cluster, because there are no hooks/notifications from the API when something is changed. Not sure how quickly you would need updates to reflect here.
