### ISSUE TITLE
Load Balancer Support

### ISSUE THREAD

**Issue by LKaemmerling** [hetznercloud/hcloud-cloud-controller-manager#48]
We have recently launched our Load Balancers: https://twitter.com/Hetzner_Online/status/1274998500623777793

Support for Load Balancers in our k8s cloud controller is already on the way. We need to polish a few things and will release the Cloud Controller then.

**Comment by ashokspeelyaal** [comment]
@LKaemmerling  @fhofherr  Thanks for the update. This will make life much easier.  Do you have any approximate timeline for this?  I am setting up a production cluster in Hetzner(using metallb and for multi-master - HAProxy and keepalived).  I simply wanted to know, if I have to use the Hetzner loadbalancer approximately how much time it is going to take.

**Comment by LKaemmerling** [comment]
> @LKaemmerling @fhofherr Thanks for the update. This will make life much easier. Do you have any approximate timeline for this? I am setting up a production cluster in Hetzner(using metallb and for multi-master - HAProxy and keepalived). I simply wanted to know, if I have to use the Hetzner loadbalancer approximately how much time it is going to take.

Give us just a few hours :)

**Comment by ashokspeelyaal** [comment]
That would be awesome :) It is worth waiting then. Thank you for your great work.

**Comment by LKaemmerling** [comment]
@ashokspeelyaal FYI, we just released the Cloud Controller: https://twitter.com/Lukas_Kae/status/1275400978418864130

**Comment by ashokspeelyaal** [comment]
@LKaemmerling Thanks a lot for the update.

**Comment by spatialy** [comment]
Hi @ashokspeelyaal have you use the LB for the ingress? can you share the way you do?

Best

**Comment by ashokspeelyaal** [comment]
@spatialy  I am using it for nginx controller (as LoadBalancer service).

https://github.com/helm/charts/tree/master/stable/nginx-ingress

For Hetzner: 
 I added annotations  to nginx-controller service and deployed to create load balancer. as mentioned in this documentation https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md

Then deploying ingress is just as usual.

**Comment by spatialy** [comment]
Hi @ashokspeelyaal we try but unsuccessfully for now.
Can you share the annotations you add to the Nginx-ingress and your load-balancer config scheme?
you are deploying one LB for each INGRESS or just one?
Sorry if some of my questions can be basic.
Best

**Comment by ashokspeelyaal** [comment]
@spatialy it is straight forward. given the annotation here. 
And For now I deploy only one nginx-controller so that i has only one real load balancer. Then Ingress is just like configurations to I use multiple ingresses.   Yes, understanding ingress vs ingress-controller is important here :) I was there a few years ago with this confusion.  

`controller:
  service:
    annotations:
      load-balancer.hetzner.cloud/location: fsn1`
