### ISSUE TITLE
Example of LB with Cert, TLS Termination, K8S

### ISSUE THREAD

**Issue by dclayton77** [hetznercloud/hcloud-cloud-controller-manager#494]
I would really like to achieve the following:

* Hetzner LB in front of my K3S cluster built via https://github.com/vitobotta/hetzner-k3s
* LB to provide a wildcard certificate so that I can have multiple services.  E.g. auth.dev.mydomain.co.uk, www.dev.mydomain.co.uk etc
* HTTPS traffic to be terminated at the LB and the traffic forwarded to the cluster.
* Client IP address should be preserved so proxy protocol needs to be enabled
* Ingress will be handled via Kong Gateway

I am confident on setting up the Kong Gateway and deployment of my individual services, deployments etc.  What I cannot figure out is how to get the load balancer setup correctly.  There are so many conflicting threads on here it is difficult to determine how to achieve this.  I also cannot find any documentation with a complete list of the annotations available which would be really helpful.

The closest I have got is with the following annotations:

```
      load-balancer.hetzner.cloud/location: nbg1
      load-balancer.hetzner.cloud/protocol: https
      load-balancer.hetzner.cloud/use-private-ip: "true"  

      load-balancer.hetzner.cloud/certificate-type: managed
      load-balancer.hetzner.cloud/http-managed-certificate-name: mydomain-dev
      load-balancer.hetzner.cloud/http-managed-certificate-acme-staging: "true"
      load-balancer.hetzner.cloud/http-managed-certificate-domains: "*.dev.mydomain.co.uk"

      load-balancer.hetzner.cloud/https-redirect-http: "true"
      load-balancer.hetzner.cloud/uses-proxyprotocol: "true"

      load-balancer.hetzner.cloud/health-check-protocol: http
      load-balancer.hetzner.cloud/health-check-http-domain: dev.mydomain.co.uk
      load-balancer.hetzner.cloud/health-check-http-path: /
      load-balancer.hetzner.cloud/http-status-codes: 200,404
```

Whilst the certificate, load balancer and services are created, the issues I have are as follows:

* Certificate is invalid
* Healthchecks all fail on the LB
* Service is responding with a 503

If anyone can provide a complete example it would be very helpful.

**Comment by Defman** [comment]
1. You certificate might be invalid due to it being issued by letsencrypt-staging and not their production issuer. Ie remove the `load-balancer.hetzner.cloud/http-managed-certificate-acme-staging: "true"`.
2. Is it a service or the load balancer responding with 503. I think you mean the lb is returning 503 and that is due to malformed/bad health checks. You might want to use `2??,3??` for health checks. The health check domain is used to set the host header.

**Comment by dclayton77** [comment]
Thank you for your response.  Due to the lack of documentation around this area and clarity over whether the feature is working, I have reverted back to using SSL termination and certificate generation via the ingress and cert-manager running within my cluster.
