### ISSUE TITLE
support baremetal servers too

### ISSUE THREAD

**Issue by pierreozoux** [hetznercloud/hcloud-cloud-controller-manager#5]
Is there a plan that the hetznercloud API will support baremetal?
If yes, what is the estimated timeline?

Then it would be nice to have this support :)

**Comment by thetechnick** [comment]
Hi @pierreozoux,
while the Hetzner Cloud API will not add dedicated servers, the [Hetzner Robot API](https://robot.your-server.de/doc/webservice/en.html#get-server) does already provide all features you might want for dedicated servers.

A Kubernetes cloud controller manager implementation for dedicated servers is not planned.
While populating the nodes labels is convenient, baremetal servers are quite static, so I don't see the benefit to use a cloud controller manager.
The job of this controller manger is to setup/delete nodes to rapid rescale a cluster.

If you don`t mind, you can share some info about your setup and use case, so I can better understand what you are wanting the controller manager for.

**Comment by pierreozoux** [comment]
Thanks for your kind answer.

I start to use:
https://github.com/xetys/hetzner-kube

And the sweet spot is to use VMs for the masters, and Baremetal for the workers.
If we could have everything automated, it would be really nice :)

But yes, I can also do it by hand.

Feel free to close the issue.
