### ISSUE TITLE
LoadBalancer service stuck at pending even though the LB has been created and has public IP

### ISSUE THREAD

**Issue by vitobotta** [hetznercloud/hcloud-cloud-controller-manager#50]
Hi, I have installed v1.6.0 in a test cluster, and the first thing I noticed is that no labels or annotations were added to the nodes, which is something that happened when I tested the controller a few months ago. In the controller log there is the error: `hcloud/instances.InstanceExistsByProviderID: hcloud/providerIDToServerID: missing prefix hcloud://: 6393937`

Then I tried to install Nginx ingress with a service of type LoadBalancer. The load balancer was created quickly and I could see from the HC console that it had a public IP, but the service got stuck at pending, without the IP. In the controller log I see this:

```
reason: 'SyncLoadBalancerFailed' Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://:
```

I added the `cloud-provider: "external"` extra arg to Kubelet before installing the controller. Not sure if it's relevant, but this is a cluster provisioned with Rancher and using Weave as CNI. Edit: Kubernetes 1.17.5.

Thanks in advance for any help.

**Comment by vitobotta** [comment]
The problem was that I updated the kubelet config *after* creating the cluster. I created a new test cluster with the `--cloud-provider=external` setting from the beginning and everything worked fine.

For those who have a similar issue with an existing cluster with Rancher, this is what I did:

1. updated the kubelet config
2. installed the cloud controller
3. created a new node pool, making sure the controller adds labels/annotations as expected (meaning that it's working)
4. drained and removed the old node pool
5. created service of type LoadBalancer.

The load balancer was correctly provisioned and I was able to use the ingress resources with Nginx just fine.

Thanks for the new release and for the load balancers!

**Comment by himanshusharma-git** [comment]
I am using RKE on hetzner and now i am stuck with the same issue , load balancer is creating but cnt get the IP address .


Events:
  Type     Reason                  Age                 From                Message
  ----     ------                  ----                ----                -------
  Normal   EnsuringLoadBalancer    25s (x5 over 102s)  service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  25s (x5 over 101s)  service-controller  Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: hcops/providerIDToServerID: missing prefix hcloud://:

**Comment by LKaemmerling** [comment]
You need to recreate the whole cluster with `--cloud-provider=external`. See Step 1 in https://github.com/hetznercloud/hcloud-cloud-controller-manager

**Comment by himanshusharma-git** [comment]
yeah i did but i also have a question now below : 
spec:
  externalID: master
  podCIDR: 10.244.0.0/24
  providerID: hcloud://123456 # <-- Server ID


it is asking for provideID and i am using multi master so do i can entry any master ip or am i still missing something ?

**Comment by LKaemmerling** [comment]
The provider ID will be set from the cloud controller :)

**Comment by ceyhunn** [comment]
Hi @vitobotta , 
I updated kubelet config of existed cluster in rancher like this:
```
kubelet:
      extra_env:
        - KUBELET_EXTRA_ARGS=--cloud-provider=external
```
Cluster and worker nodes updated, but error doesn't disappear. What I missed?

**Comment by ceyhunn** [comment]
@vitobotta , I notice that `--cloud-provider=external ` has not been set in kubelet command:
`/opt/rke-tools/entrypoint.sh kubelet --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --cloud-provider= --resolv-conf=/etc/resolv.conf`
