### ISSUE TITLE
Readme update for new community pacakges

### ISSUE THREAD

**Issue by dominic-p** [hetznercloud/hcloud-cloud-controller-manager#513]
When I updated to the [new community host APT repo](https://kubernetes.io/blog/2023/08/31/legacy-package-repository-deprecation/), my CCM managed load balancers started getting 0 targets. After some digging, it looks like the issue had to do with the env variable config (`KUBELET_EXTRA_ARGS=--cloud-provider=external`). The systemd override described in the readme no longer worked to set the variable for me.

The new deb package includes a file /etc/sysconfig/kubelet with the contents `KUBELET_EXTRA_ARGS=` (see [this comment](https://github.com/kubernetes/release/issues/3219#issuecomment-1717015276)). I'm not sure if this takes precedence over the systemd config or if I just had my override setup incorrectly. Either way, I thought it would be worth bringing to your attention.

**Comment by apricote** [comment]
Looks like this will be [fixed upstream](https://github.com/kubernetes/release/issues/3276#issuecomment-1721595323) for new releases.

I think nowadays a better way to set this flag is through the kubeadm [`InitConfiguration.nodeRegistration.kubeletExtraArgs`](https://kubernetes.io/docs/reference/config-api/kubeadm-config.v1beta4/#kubeadm-k8s-io-v1beta4-NodeRegistrationOptions).

**Comment by dominic-p** [comment]
Thanks for looking into that, and I agree about the kubeadm config being a better solution. I didn't realize you could use it to set the extra args. That's awesome.

**Comment by dominic-p** [comment]
I saw this was marked as stale. Should we update the readme to reference `InitConfiguration.nodeRegistration.kubeletExtraArgs` instead of the systemd drop in? Or, since it's working now, should we just close this?

**Comment by apricote** [comment]
Added  a reference to kubeadm config in #607.
