### ISSUE TITLE
Docs for LBIPv6Disabled 

### ISSUE THREAD

**Issue by guettli** [hetznercloud/hcloud-cloud-controller-manager#517]
Please elaborate this comment:

```

	// LBIPv6Disabled disables the use of IPv6 for the Load Balancer.
	//
	// Set this annotation if you use external-dns.
	//
	// Default: false.
	LBIPv6Disabled Name = "load-balancer.hetzner.cloud/ipv6-disabled"
```

Does this refer to the IP of LB, or the IPs of the LB targets?

I can create a PR, just leave the answer in this ticket. Thank you.

**Comment by apricote** [comment]
Hey @guettli, the docs for this annotation are really missing the point.

If the annotation is set, the IPv6 address of the LB is _NOT_ written back into the Kubernetes `Service` resource at `.status.loadBalancer.ingress`. By default this list of ingress addresses includes the IPv4 & IPv6 addresses.

**Comment by apricote** [comment]
Hey @guettli, is the offer to create a PR still standing?

**Comment by guettli** [comment]
@apricote thank you for asking. I have no experience with ipv6 and Kubernetes. Maybe it is better if you (or a team mate) documents it.
