### ISSUE TITLE
Nameserver limit exceeded

### ISSUE THREAD

**Issue by MichaelVoelkel** [hetznercloud/hcloud-cloud-controller-manager#533]
So Hetzner chooses to give two nameservers which will result in four entries in /run/systemd/resolver/resolv.conf, thanks for nothing.

This seems to block cloud-controller-manager as it needs fewer entries.

Manually changing the number of entries in this file has no effect. I thought, restarting systemd.resolver would do the trick but it will then just overwrite the file again, sigh...

So how to solve this?

(PS: via search I found this: https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/275 but it gives no useful advice how to solve it)

**Comment by apricote** [comment]
Hey @MichaelVoelkel,

are you talking about this warning message?

```
Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 2a01:4ff:ff00::add:2 2a01:4ff:ff00::add:1 185.12.64.2
```

This warning is actually benign and more about a bug in libc than anything else. Kubernetes still works as expected, but only passes 3 out of the 4 defined Nameserver IPs to Pods.

> This seems to block cloud-controller-manager as it needs fewer entries.

What issues do you see with HCCM? The warning message should show up for every single Pod, not only HCCM.

**Comment by MichaelVoelkel** [comment]
Having looked deeper (that is, into the actual logs of the container), there was actually a very different problem.

Still, is it not a problem if only 3/4 nameservers are transmitted?

Another problem was that not all env vars from some tutorial were really moved to kubelet, in particular the right resolv.conf. The right resolv.conf also has four namesevers but for some reason this does not lead to errors.

So, not sure, but yeah, latest info seems to indicate it's not on this CCM...

**Comment by apricote** [comment]
> Still, is it not a problem if only 3/4 nameservers are transmitted?

Multiple nameservers are provided for redundancy reasons. Removing one IP from the list might reduce the total availability, but as long as there is still one server available this should not be a  problem.

Closing as there is no evident issue with HCCM
