### ISSUE TITLE
Set IPv6 PodCIDR

### ISSUE THREAD

**Issue by simonostendorf** [hetznercloud/hcloud-cloud-controller-manager#543]
Is there a way that the hcloud ccm can add the node-specific ipv6 public subnet to `spec.podcidrs` so that CNIs like cilium can use this subnet to assign ipv6 addresses to pods? (especially with cilium's `ipam.mode=kubernetes` option)

Or is the cloud controller manager the wrong place for this solution? I read online that public subnets are best practise for ipv6 only / dual stack clusters so the cloud controller manager should be the bridge between hcloud and the cluster :)

**Comment by apricote** [comment]
Hey @simonostendorf,

Assigning PodCIDRs is usually the responsibility of the IPAMController in `kube-controller-manager`. It assigns ranges from the `--cluster-cidr` that it is configured with: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack

Right now we only implement the [`k8s.io/cloud-provider.Interface`](https://github.com/kubernetes/cloud-provider/blob/c4e2684a2292550a73ffc14dc81a4c22377e76d3/cloud.go#L42-L69) (and its sub-interfaces), and IPAM is not one of them. It is technically possible to add more controllers to hccm. It is also possible to setup a small controller using `controller-runtime` that handles this outside of HCCM.

**Comment by simonostendorf** [comment]
> Assigning PodCIDRs is usually the responsibility of the IPAMController in `kube-controller-manager`. It assigns ranges from the `--cluster-cidr` that it is configured with: https://kubernetes.io/docs/concepts/services-networking/dual-stack/#configure-ipv4-ipv6-dual-stack

Using this was my first choice but it didn't work for me because nodes get a /64 subnet and kubernetes needs the podSubnet to be >= 108 (I didn't find this in the docs but I get an error when I try to use a /64 subnet). After changing the subnet to 112 I get an error that the node subnet is /64 and the podSubnet is 112 and that they need to be the same size. 
So I thought there should be another option where I leave the podSubnet config empty and assign the ipv6 subnet to each node via a controller. 

Thanks for the details, maybe I will create a small controller or fork the hccm to add a controller there (to keep the hcloud logic in one place) :)

**Comment by simonostendorf** [comment]
I've done some more testing and I'm using a private ipv6 range instead of a public one. This is not what I originally wanted, but it works :D
