### ISSUE TITLE
Missing providerID, labels and annotations

### ISSUE THREAD

**Issue by morsik** [hetznercloud/hcloud-cloud-controller-manager#567]
Hi,

I created cluster with kubeadm, added this controller manager and while it works (configures Load Balancer in Hetzner and routes in Network), it didn't configure `providerID, labels and annotations as mentioned in [Readme Features](https://github.com/hetznercloud/hcloud-cloud-controller-manager#features).

Of course, load balancer configuration didn't work properly without `providerID` - when I added it manually, then Load Balancer was correctly configured, but labels are still not there :/

I have my `kubelet` running on everynode with `--cloud-provider=external`.

```
[root@kube-node-arm-2 ~]# cat /etc/sysconfig/kubelet
KUBELET_EXTRA_ARGS="
  --kube-reserved=cpu=50m,memory=50Mi,ephemeral-storage=1Gi
  --system-reserved=cpu=50m,memory=100Mi,ephemeral-storage=4Gi
  --cloud-provider=external
"
```

```
[root@kube-node-arm-2 ~]# ps auxf | grep 'kubelet '
root      209892  0.0  0.0   6112  1764 pts/0    S+   10:32   0:00  |           \_ grep --color=auto kubelet
root      189715  2.4  3.1 1778652 113872 ?      Ssl  09:18   1:47 /usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///var/run/crio/crio.sock --pod-infra-container-image=registry.k8s.io/pause:3.9 --kube-reserved=cpu=50m,memory=50Mi,ephemeral-storage=1Gi --system-reserved=cpu=50m,memory=100Mi,ephemeral-storage=4Gi --cloud-provider=external
```

I'm out of ideas, everything "seems" to be fine on my side in terms of configuration so... maybe something changed and it's a bug? Or some undocumented edge-case on my side?

Versions:
- Alma Linux 9
- Kubernetes 1.28.4 (all installed at the same day)
- Hetzner Cloud Controller Manager - `hetznercloud/hcloud-cloud-controller-manager:v1.18.0` installed via Helm

**Comment by apricote** [comment]
Hey @morsik,

Is the taint [`node.cloudprovider.kubernetes.io/uninitialized`](https://kubernetes.io/docs/reference/labels-annotations-taints/#node-cloudprovider-kubernetes-io-uninitialized) still set on your nodes? This taint is added by the kubelet when it first starts and creates the Node, but only if the initial start is done with the flag `--cloud-provider=external`. We only set the Provider ID & Taints on the first reconcile, if this taint is set. After that we (or rather the `kubernetes/cloud-provider` library we use) considers the node "initialized" and this is not being checked again.

Could you post the logs of hcloud-cloud-controller-manager during the first few minutes after adding a new node?

**Comment by morsik** [comment]
@apricote nope, I never saw such taint. The only taint I had was standard `node-role.kubernetes.io/control-plane:NoSchedule`.

```
morsik@Star-Destroyer ~ $ kubectl describe nodes | grep Taint -A2
Taints:             <none>
Unschedulable:      false
Lease:
--
Taints:             <none>
Unschedulable:      false
Lease:
--
Taints:             <none>
Unschedulable:      false
Lease:```

Also:

> Could you post the logs of hcloud-cloud-controller-manager during the first few minutes after adding a new node?

Does this mean, that if node was in "wrong" state when adding, then it'll be never fixed and I have to reinitialize nodes?

**Comment by apricote** [comment]
You _should_ be able to manually add the taint to the affected nodes, which should [retrigger the initialization by us](https://github.com/kubernetes/cloud-provider/blob/master/controllers/node/node_controller.go#L414), but I have not tested this before, if this is a production cluster, you might want to test it in another cluster first.

```
kubectl taint node your-node-name node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
```

**Comment by morsik** [comment]
@apricote I just created new node with all settings correct, and it indeed created missing labels/annotations/providerID so it looks like it works properly when everything is correct, but after you do any kind of mistake, it doesn't recover...

But thank you for this tip!
Tainting node indeed retriggered initialization and now all missing stuff appears and everything is configured properly!

I'm closing this then since it's not a bug in software, but it would be good to add this to documentation.
