### ISSUE TITLE
feat(robot): Support Private Networks & Routing

### ISSUE THREAD

**Issue by jahanson** [hetznercloud/hcloud-cloud-controller-manager#571]
When hccm tries to provision and add the server meta data it tries to match the IPs. In my case the main IP is private but as previously stated in a few different issues the robot client can't retrieve vswitch/private IPs so it ultimately fails and ignores provisioning the server metadata even though the hostnames match on robot and on the node.

![Screenshot from 2023-11-29 14-42-17](https://github.com/hetznercloud/hcloud-cloud-controller-manager/assets/1548511/ab31391a-9651-4b1c-8168-88e997d73bc7)

Is there any way we can ignore the ip matching on robot since the hostname matching is usually enough?

**Comment by jahanson** [comment]
Hey @apricote, I am using the unreleased Robot support from this repo. I am currently using cilium between all nodes so disabling the networking function for hccm is no problem. I didn't know however that the logs I provided were from `kubernetes/cloud-provider`. 

Setting a node label for private ips would be great. I appreciate your work on this! If there's anything I can do to help let me know

**Comment by apricote** [comment]
Great to hear that you are using it already!

The code that fails for you is here: https://github.com/kubernetes/cloud-provider/blob/152995bd25ae20bc618a9ba7039a1b683372c86c/node/helpers/address.go#L131-L134

I plan on talking to the team responsible for Networks next week, to discuss how well we can integrate it. I can not yet promise anything, and it will probably not be included in the next release (planned for the coming week).

**Comment by apricote** [comment]
Right now it is not possible to configure Routes using vSwitch IPs as Gateway. This is a strict requirement for enabling the Routes functionality.

**Comment by lukasmetzner** [comment]
Hey,

We are happy to announce that we improved our Robot support in HCCM version [v1.24.0](https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/tag/v1.24.0). The HCCM now forwards `InternalIPs` by default on Robot nodes when the `--node-ip` flag is used. If the provided IP is not already registered as an `ExternalIP` and matches the expected address family, it will be forwarded automatically during initialization.

This allows the use of vSwitch IPs in private networks and Load Balancers.

This does not change anything with respect to the restrictions of the routing capability. This is still not supported by the underlying product.

Best Regards,
Lukas
