### ISSUE TITLE
Clarification about network overlapping

### ISSUE THREAD

**Issue by rlex** [hetznercloud/hcloud-cloud-controller-manager#576]
Hello, reading through docs, especially this https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/deploy_with_networks.md file, i got confused about following parts:

In example, it recommends creating network 10.0.0.0/8 (pretty wide one)
In same example, it says that cluster-cidr is using 10.244.0.0/16 (which falls under 10.0.0.0/8)

And in the end of doc, it states:

```
Solution: Make sure the cluster-cidr does not overlap with the Hetzner Cloud Network. For example your Subnetwork could be 10.10.10.0/24 when the cluster-cidr is set to 10.244.0.0/16.
```

So should it overlap with some of k8s networks or not? 

Say i created 10.121.0.0/16 network in hetzner, assigned 10.121.0.{2..9} IPs to node as internal IP, and decided my cluster cidr will be 10.251.0.0/16. Is that correct setup?

**Comment by apricote** [comment]
> Networks should overlap, but subnet for podIP subnet should not exist in hetzner network "subnets"

Yup, thats it. I will update the docs to make this clearer, perhaps add an example.

> Not sure if service-cidr should be part of that network, probably not.

There should be no routes in Hetzner Cloud Network for the `service-cidr`, so it does not matter if its inside the Network CIDR or not. As long as you do not have a Subnet that overlaps with it.

For my own cluster I have it inside the Network CIDR. But I am no network expert, so take this with a grain of salt ;)

**Comment by apricote** [comment]
@rlex Could you take a look at https://github.com/hetznercloud/hcloud-cloud-controller-manager/pull/577 and give some feedback if this would have helped you?
