### ISSUE TITLE
New robot node kicked out when joining an established cluster

### ISSUE THREAD

**Issue by jahanson** [hetznercloud/hcloud-cloud-controller-manager#578]
## Problem
I had hccm already in the cluster and then when I tried to join a new robot server it the cluster it was deleted since it wasn't found in the cloud servers.

## Work around
Scale hccm to 0 and set the `provisionID: hrobot://#servernumber` and scale it back to 1. I didn't think to grab the log message also but I did get a clip of the node being evicted once it joined.
[Screencast from 2023-12-01 22-45-37.webm](https://github.com/hetznercloud/hcloud-cloud-controller-manager/assets/1548511/dcef09e3-8b3e-4cd8-8df5-6c7141937b80)

**Comment by apricote** [comment]
Some questions:

- Did this only happen once or can you reproduce this?
- Did the server/node follow the [naming guidelines](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/docs/robot.md#identifying-the-correct-server)? (Node Name == Host Name == Name in Robot)

I am afraid this will be very hard to debug without any logs from hcloud-cloud-controller-manager.

**Comment by apricote** [comment]
Forgot to put this in the original message, but this is exactly the behaviour in our [e2e tests]https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/.github/workflows/test_e2e.yml#L148-L188), just with k3s vs Talos:

1. Setup Cluster with Cloud Nodes
2. Deploy HCCM
3. Add Robot Server
4. Verify Robot server is successfully initialized and can be added to Load Balancer

**Comment by jahanson** [comment]
I will be re-provisioning my cluster today and see if I can re-produce with some logs

**Comment by jahanson** [comment]
> Forgot to put this in the original message, but this is exactly the behaviour in our [e2e tests](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/main/.github/workflows/test_e2e.yml?rgh-link-date=2023-12-06T09%3A27%3A53Z#L148-L188), just with k3s vs Talos:
> 
> 1. Setup Cluster with Cloud Nodes
> 2. Deploy HCCM
> 3. Add Robot Server
> 4. Verify Robot server is successfully initialized and can be added to Load Balancer

@apricote I haven't forgotten about this, I have just been doing quite a bit of debugging. It seems I just need to scrap any sort of private ips at all or else the nodes keep getting removed. I have two IPs on my talos nodes. A private one and a public one. The hostname matches robot but the private is set in the /etc/hosts file since it's the recognized node ip automatically so I suppose that's what's causing the mismatch and removal of nodes.
![image](https://github.com/hetznercloud/hcloud-cloud-controller-manager/assets/1548511/4eaca191-4cd0-4036-9197-10b8dc8151f2)
I presume this is the root of my issue and the cluster will fully initialize once I've re-configured the ip addresses but that will take more time.

Thank you for your time on this; I'll re-open or create a new issue if I have any further problems with this.
