### ISSUE TITLE
LoadBalancers: Provide an option for disabling LoadBalancer management

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/hcloud-cloud-controller-manager#62]
Hey,

I'm trying to set up a Kubernetes Cluster which has the hcloud-cloud-controller-manager installed. As expected, the hcloud-cloud-controller-manager will try to map my Kubernetes LoadBalancers to a Hetzner LoadBalancer. However, I would like to let MetalLB do that job in my case. Is there any way to prevent hcloud-cloud-controller-manager from grabbing a certain Kubernetes Loadbalancer? How can I define which LoadBalancer should be handled by which controller?

Best regards
Matthias

**Comment by LKaemmerling** [comment]
I don't think that this is possible. MetalLBs use case is intended for "bare metal clusters" so deploy clusters on bare metal. So i don't think it is possible to have MetalLB and our Load Balancers (or any other Load Balancer). We added a new ENV (HCLOUD_LOAD_BALANCERS_ENABLED) flag to the latest version (will be released officially soon). Therefore you can disable the whole Hetzner Cloud Load Balancers managing. 

#63

**Comment by MatthiasLohr** [comment]
Ok, perfect, that would do the job. Thanks!

**Comment by andriuspl** [comment]
@MatthiasLohr have you succeeded with Metallb on Hetzner Cloud?

**Comment by MatthiasLohr** [comment]
To be honest: No idea. Too much time has passed.

**Comment by maulerjan** [comment]
multiple haproxy instances with keepalived and a hook for reassigning Floating IP is the only reliable way to have HA setup without using Hetzner's load balancer.
