### ISSUE TITLE
Not possible to configure the annotation load-balancer.hetzner.cloud/health-check-port

### ISSUE THREAD

**Issue by BWagener** [hetznercloud/hcloud-cloud-controller-manager#64]
As far as I can tell there is no working way to specify the health-check-port the controller should configure.

* it's not possible to set it as an integer. From what I found only strings are allowed in annotations/labels (https://github.com/kubernetes/kubernetes/issues/57509)
* if it's not an integer the controller doesn't process the annotation

https://github.com/hetznercloud/hcloud-cloud-controller-manager/commit/df90212c1c022a1cb892c19466d6efa38cb925f2#r40335885

**Comment by LKaemmerling** [comment]
You need to set all health check based annotations:
```
    load-balancer.hetzner.cloud/health-check-interval: 10s
    load-balancer.hetzner.cloud/health-check-port: "2020"
    load-balancer.hetzner.cloud/health-check-retries: "3"
    load-balancer.hetzner.cloud/health-check-timeout: 10s
```

(As a sample)

**Comment by BWagener** [comment]
Thank you! That did the trick. Much appreciated!

**Comment by fhofherr** [comment]
Hi @BWagener,

we still need to fix the underlying issue :slightly_smiling_face: I'm therefore re-opening your ticket to help us keep track of it.
