### ISSUE TITLE
Helm Chart?

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/hcloud-cloud-controller-manager#65]
Hi,

are you planning to provide a Helm Chart for installing hcloud-cloud-controller-manager? If not, I would provide one if you are interested.

Best regards
Matthias

**Comment by MatthiasLohr** [comment]
Ok, I couldn't wait. Here it is:

https://gitlab.com/MatthiasLohr/hcloud-cloud-controller-manager-helm-chart

Would you like to link it somewhere?

**Comment by MatthiasLohr** [comment]
By the way: Is there any chance of having a nice logo? Not sure if it's desired/allowed by Hetzner to use the original Hetzner logo, also no idea about a modified logo which expresses the relation between the Helm Chart and this project. I'm open for any suggestions.

**Comment by LKaemmerling** [comment]
We have at the moment no plan to provide an official Helm Chart. We might reconsider this in the future. Of course, you can (as you already did) host a custom helm chart.

**Comment by MatthiasLohr** [comment]
@LKaemmerling, thanks for answering. Is there any chance that I get a permit to use (a variant of?) the hetzner logo? Then it looks more "ready" in lists like e.g. https://artifacthub.io/packages/search?page=1&text=cloud.

**Comment by LKaemmerling** [comment]
Please ask this per Support Ticket.

**Comment by MatthiasLohr** [comment]
FYI: I also created a Helm Chart for easy CSI Driver setup: https://gitlab.com/MatthiasLohr/hcloud-csi-driver-helm-chart

**Comment by MatthiasLohr** [comment]
> Please ask this per Support Ticket.

I didn't get *any* reply now since two weeks...
