### ISSUE TITLE
Controller support for private networks

### ISSUE THREAD

**Issue by kyrbrbik** [hetznercloud/hcloud-cloud-controller-manager#666]
Hi,
we want to use the LoadBalancer feature of the controller, but I'm having problem with installing it. We have a kubernetes cluster that is running on nodes with only private IP addresses and I think that it fails when trying to find the external IP to assign to each node.

```
E0617 10:41:19.447359       1 node_controller.go:240] error syncing 'test-1': failed to get node modifiers from cloud provider: provided node ip for node "test-1" is not val
id: failed to get node address from cloud provider that matches ip: 192.168.20.11, requeuing
I0617 10:41:19.447678       1 node_controller.go:431] Initializing node test-2 with cloud provider
E0617 10:41:19.608387       1 node_controller.go:240] error syncing 'test-2': failed to get node modifiers from cloud provider: provided node ip for node "test-2" is not val
id: failed to get node address from cloud provider that matches ip: 192.168.20.12, requeuing
```

I tried to enable networks if that would help with this but this fails as well

``` 
I0617 10:43:44.966956       1 metrics.go:69] Starting metrics server at :8233
F0617 10:43:45.051098       1 main.go:67] Cloud provider could not be initialized: could not init cloud provider "hcloud": hcloud/newCloud: Network 4345735
 not found
```

The network exists because when I try to list it with hcloud cli I can see it 
```
ID        NAME                 IP RANGE          SERVERS     AGE
4345735   TestNetwork          192.168.20.0/24   4 servers   1h
```

The cluster is running kubernetes 1.29.5 installed with kubespray, CNI is calico and the --cloud-provider=external setting appears to be applied correctly.

So my two questions why is the controller unable to find the network and is it even possible to run the controller in the setup.
Thanks

**Comment by apricote** [comment]
Hey @kyrbrbik,

> why is the controller unable to find the network 

That is a very good question. You do need to set the network ID in HCCM for this to work.

- What version of HCCM are you using?
- Are you sure that the API token you gave to HCCM is for the correct project?
- Could you set the environment variable `HCLOUD_DEBUG=1` on the hcloud-cloud-controller-manager deployment? This will enable logs for all HTTP requests made to our API. Can you post the first few requests after starting HCCM with this variable? It should include a `GET /v1/networks/4345735` request + response.

You can also open a [support ticket](https://console.hetzner.cloud/support) and attach the logs there if you want to keep them private. The API Token is redacted from the logs either way.

**Comment by kyrbrbik** [comment]
Well it was a mistake on my end the network id contained some white space character that wasn't visible in the logs until I turned on the debug logs.

Now it seems to be working correctly. Thanks.
