### ISSUE TITLE
Load Balancer with ACME / Let's Encrypt

### ISSUE THREAD

**Issue by niklaskorz** [hetznercloud/hcloud-cloud-controller-manager#67]
I understand if this is out of the scope of the controller manager, which is why I'd like to ask a few questions that'd allow me to implement a cron job for automatic TLS certificates for the load balancer:

1. Can the content of a certificate resource in the Hetzner API somehow be exchanged or would this require creating a new certificate resource? The API docs only mention `name` and `labels` in the update endpoint.
2. If not, can the list of certificate IDs the load balancer uses be updated without introducing downtime in the load balancer itself?

In particular, I'd like to implement the Let's Encrypt DNS challenge through a Kubernetes cronjob using the Hetzner DNS API and then exchange the certificate the load balancer uses without downtime.

**Comment by LKaemmerling** [comment]
Hey @niklaskorz,

1): You need to create a new resource
2): The downtime required for this should be pretty low (a few seconds). You can easily change the annotation on the service and everything is handled behind the scene. After that, you can delete the old certificate.

**Comment by LKaemmerling** [comment]
I will close the issue as it is now, as the question itself was answered. We are looking into adding Let's Encrypt support to our cloud.
