### ISSUE TITLE
Share same load balancer for multiple services

### ISSUE THREAD

**Issue by eedugon** [hetznercloud/hcloud-cloud-controller-manager#68]
Is there any way to make kubernetes reuse / configure the same LoadBalancer for multiple services as soon as each service is configured in different ports?

I see that the Load Balancers in the Cloud UI accept up to 5 services definition. If I have understood correctly the goal of defining multiple services in a load balancer, I guess it would be nice to be able to achieve this configuration directly via annotations in the k8s services.

For example with `metallb` we can do something like `metallb.universe.tf/allow-shared-ip: "float-ip"` to reuse the same external IP for multiple services (of course the ports cannot be reused).

I have tried setting the same `load-balancer.hetzner.cloud/name` annotation in 2 services but one of them overrides the definition of the other and I end up with only one service really working.

Apologize if i'm missing anything and the question has no sense ;)

**Comment by LKaemmerling** [comment]
Hey, sorry for the late reply. 

One Load Balancer supports only one Load Balancer Service within k8s. You could use an ingress controller behind the LB to make it work with multiple services.
