### ISSUE TITLE
SyncLoadBalancerFailed 

### ISSUE THREAD

**Issue by wfrank2509** [hetznercloud/hcloud-cloud-controller-manager#69]
Hello,

I followed the instructions described in this blog https://community.hetzner.com/tutorials/install-kubernetes-cluster.

Everything went pretty smooth and the cluster looks like it is set up ok. Unfortunately wehen deploying something with type=Loadbalancer after getting the external IP the service is not responding.

`
root@master-1:~# kubectl describe services my-service
Name:                     my-service
Namespace:                default
Labels:                   app.kubernetes.io/name=load-balancer-example
Annotations:              <none>
Selector:                 app.kubernetes.io/name=load-balancer-example
Type:                     LoadBalancer
IP:                       10.108.68.170
LoadBalancer Ingress:     xxx.xx.xxx.xx
Port:                     <unset>  8080/TCP
TargetPort:               8080/TCP
NodePort:                 <unset>  31417/TCP
Endpoints:                10.244.3.10:8080,10.244.3.11:8080,10.244.3.12:8080 + 2 more...
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type     Reason                  Age                    From                Message
  ----     ------                  ----                   ----                -------
  Warning  AllocationFailed        4m21s (x2 over 4m21s)  metallb-controller  Failed to allocate IP for "default/my-service": no available IPs
  Normal   IPAllocated             2m9s                   metallb-controller  Assigned IP "xxx.xx.xxx.xx"
  Normal   nodeAssigned            2m9s                   metallb-speaker     announcing from node "worker-3"
  Normal   EnsuringLoadBalancer    106s (x6 over 4m21s)   service-controller  Ensuring load balancer
  Warning  SyncLoadBalancerFailed  106s (x6 over 4m21s)   service-controller  Error syncing load balancer: failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.Create: neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set
`

I recheck the walkthrough instructions and made sure I did all in the same order as described.

I am not sure what to check or how to debug that properly. Hope you can help pointing me in the right direction.

**Comment by LKaemmerling** [comment]
Hello @wfrank2509,

you are missing the annotation for the location or the network-zone. Please have a look at: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/load_balancers.md (You can see this also in your error message: `neither load-balancer.hetzner.cloud/location nor load-balancer.hetzner.cloud/network-zone set`)

**Comment by lukasmetzner** [comment]
I saw there is a left over `TODO`. Fixed in #1018. File already exists at `reference/load_balancer_annotations.md`.
