### ISSUE TITLE
Nodes get assigned the VPS public IP and not the VPS internal IP if using networks.

### ISSUE THREAD

**Issue by bpasson** [hetznercloud/hcloud-cloud-controller-manager#71]
I have all nodes attached to a private network and rather have them use that IP instead of the public IP. Can the cloud controller do this? It is far more secure to have everything bound to an internal IP instead of a public IP.

**Comment by bpasson** [comment]
I see there is code in the controller to make this work, but for some reason the ip does not get assigned. Investigating further.

**Comment by bpasson** [comment]
Further investigation made clear there seemed to be connection issues with the api-server from pods on the hostnetwork. To get around that I placed the cloud controller on the master node, as the API server is there. This resolved the connection issues. Now the nodes get 2 ips.

Still the question remains how the get the nodes to have only assigned an internal IP?

**Comment by LKaemmerling** [comment]
Do you use the  Cloud Controller with private network support? Then the Node should always get its private IP, otherwise, we don't set a private IP 

https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/hcloud/instances.go#L154

**Comment by bpasson** [comment]
They have the private IP, but also the public IP. If the public IP is not used for anything that is fine, else I'd like to have only a private IP. Not sure what the external IP is used for.

**Comment by bpasson** [comment]
Closing this issue, as the way it works is how it is specified by the cloud controller spec from Kubernetes.
