### ISSUE TITLE
Assign static IP address to kubernetes cluster

### ISSUE THREAD

**Issue by icarus42** [hetznercloud/hcloud-cloud-controller-manager#76]
Hello everyone,

I set up a kubernetes cluster on the Hetzner cloud and I want to run a web service in that cluster. Therefore I want to make the cluster accessible from the internet. Since I want this web service to be accessible through a domain, I need a public static IP to direct the traffic to. Initially I thought I could achieve this with the following setup:

```
[Internet] 
    -> [Hetzner cloud load balancer (with fixed static IP)] 
    -> [Ingress controller (e.g. traefik or nginx)] 
    -> [Kubernetes service for my web service] 
    -> [Pods for my web service]
```

My problem is that the load balancer is created dynamically and is assigned some IP I cannot control. I create the load balancer by deploying the Ingress controller's service resource (with `spec.type = LoadBalancer`). 

I read the [Hetzner Cloud load balancer documentation](https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/v1.7.0/docs/load_balancers.md) as well as the [annotation documentation](https://pkg.go.dev/github.com/hetznercloud/hcloud-cloud-controller-manager/internal/annotation?tab=doc). It seems that non of the following alternatives I can think of are possible:

1. Specify an existing Hetzner cloud load balancer to use. This would enable me to reuse this load balancer (and thereby its IP) in case I need to rebuild the kubernetes cluster.
2. Specify a Hetzner cloud floating IP to use as static IP for the dynamically created LB, e.g. by referring to that reserved floating IP in the service resource [similar to what is possible in Google's GKE](https://cloud.google.com/kubernetes-engine/docs/tutorials/configuring-domain-name-static-ip?hl=de) by setting the service's `spec.loadBalancerIP` accordingly.
3. Assign a Hetzner cloud floating IP to the dynamically created load balancer via the HCloud web interface / API. This is not possible as floating IPs can only be assigned to nodes, not load balancers. However, I would like to avoid this approach anyway since I prefer to manage this using Kubernetes resources only.

Am I missing something or are the Hetzner Cloud load balancers that just left the beta phase are not (yet) supporting this scenario?

**Comment by codeagencybe** [comment]
I'm also in the same boat as you. Trying to figure out how the static/dynamic part can be managed in a clear way. 
I have several applications that use different ingress (nginx, openlitespeed, apache) and I'm also trying to get it mixed together in a way that makes sense for my setup. 

I think some parts are just not implemented yet in the HCLOUD controller, but I'm not sure. If I'm not mistaken, in one of the other issues somebody was asking for using labels on the LB and that part was also not available yet. 
So maybe we need to give Hetzner some more time to come up with this feature set. 

For the time being, I'm considering spinning up a HAproxy LB service and use that temporary. 
Latest HAproxy 2.2 also supports now SSL dynamic storage. 
In fact, Hetzner LB is nothing more than a high available managed HAproxy instances, so you could also spin up them yourself on 3x CPX11 (if you want HA) or just use 1 CPX11 if you don't bother about HA. 
https://www.haproxy.com/blog/announcing-haproxy-2-2/

**Comment by icarus42** [comment]
Thanks for sharing your ideas.

I am currently working on a low-cost (very) small-scale deployment High availability is not what I seek. 

For this very specific scenario I found an approach to assign a static IP which is easy to set up for a single worker node "cluster". My ingress service runs on the only worker node and is bound to an external IP using `spec.externalIPs: [ < floating ip goes here > ]` (see the [kubernetes documentation](https://v1-18.docs.kubernetes.io/docs/concepts/services-networking/service/#external-ips) for details). This IP is an Hetzner floating IP. Note that this requires 

1. on the one hand changes to the worker node's network interfaces settings (see [Hetzner HCloud documentation on "Floating IP Persistent"](https://docs.hetzner.com/de/cloud/floating-ips/persistent-configuration/) for how to achieve this) and 
2. on the other hand the assignment of the floating IP to the worker node (e.g. manually via the web interface or automatically via the API). 

However, I would still prefer a load balancer. Not for the load balancing but for the flexibility when adding more servers. With the above proposed approach, I think one could also handle multiple nodes, but one would need to pin the ingress service to the worker node the floating IP is assigned to. The load balancer could provide the benefit that the ingress service could be rescheduled, e.g. in case of a node failure, while being accessible through the same IP as before (the load balancer's IP).

**Comment by LKaemmerling** [comment]
@icarus42 you could use the name annotation to set a specific load balancer (name) for a service.
``
LBName Name = "load-balancer.hetzner.cloud/name"
``

Please keep in mind, that this will only work with one service atm, as the Cloud Controller itself always "sync" the state between the k8s service it is attached to and the service(s) within the Cloud API.  We have a similar setup where the LB is the only way in (before an Nginx ingress), so the LB "only" expose Port 80 & Port 443.

**Comment by LKaemmerling** [comment]
I will close this issue because of the lack of activity. If you still encounter this problem, feel free to write again and reopen this issue.

**Comment by Ks89** [comment]
I'm having the same problem. How can I assign a static IP to my load balancer?
Which is the right answer to this question?

Every time I re-deploy my service of type LoadBalancer I get a new LoadBalancer on Hetzner gui with a different IP. However I need this public IP to be accessible from outside with a fixed ipv4, otherwise a cannot assign it as DNS to my domain.
