### ISSUE TITLE
Feature Request: Node Autoscaler

### ISSUE THREAD

**Issue by MatthiasLohr** [hetznercloud/hcloud-cloud-controller-manager#81]
With this ticket, I want to suggest to support Node Autoscaling with the hcloud-cloud-controller-manager.

When a Kubernetes cluster runs out of resources (CPU, RAM), new nodes need to be added. It would be awesome if this could be done automatically instead of manually.

hcloud-cloud-controller-manager already supports removing deleted nodes from the Kubernetes cluster, why not supporting also adding nodes, maybe even automatically. Yes, this might be more work compared to removing nodes, but I think all fundamental requirements are already here. hcloud-cloud-controller-manager already has access to the API and therefore can create new servers. Somehow, it's needed to define

  * Region
  * Operating System
  * Machine Type
  * SSH Keys
  * Name/Name Template

These parameters could be provided by annotations or a ConfigMap to the hcloud-cloud-controller-manager.

Network ID is already provided to the controller (if there is any configured). cloud-init configuration could be used for directly joining the cluster after the new machine is up.

Any thoughts about this?

Best regards
Matthias

**Comment by malikkirchner** [comment]
This would be greatly appreciated!

**Comment by codeagencybe** [comment]
I think you can already do this with HPA (Horizontal Pod Autoscaler). 
Depending on the metrics you set, it will scale up/down your nodes. 

If you have the Hetzner node drivers installed, then the feature is possible to have auto scaling nodes already. 

https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/

This driver can be used with Rancher as example
https://github.com/mxschmitt/ui-driver-hetzner

**Comment by niklaskorz** [comment]
We (@alugha) have implemented the cloudprovider interface of https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler for Hetzner and have been successfully using it for autoscaling on Hetzner Cloud since April. It still has to be adapted to Kubernetes 1.19 (currently using 1.17) but afterwards I see no reason why this couldn't be proposed upstream to be merged into the cluster-autoscaler.
If there's interest, I can publish our current fork of autoscaler here on Github as well before working on a proper pull request.

**Comment by MatthiasLohr** [comment]
I'm always a friend of Open Source, so why not providing it to the public anyways? :smile:

**Comment by identw** [comment]
I also implemented hetnzer support for autoscaling the cluster. There was no time for a pull request yet, but you can try it https://github.com/identw/autoscaler/tree/hetzner/cluster-autoscaler/cloudprovider/hetzner. 
I am new to golang so my code may not be very pretty, however I am using my cluster autoscaler in my clusters, works fine.

**Comment by LKaemmerling** [comment]
Auto-Scaling is unfortunately out of the scope of a Cloud Controller Manager (https://github.com/kubernetes/cloud-provider/blob/master/cloud.go).

**Comment by Bessonov** [comment]
There is also a pull request: https://github.com/kubernetes/autoscaler/pull/3640/
