### ISSUE TITLE
ERROR: Job failed (system failure): prepare environment: error dialing backend: dial tcp 10.0.0.5:10250: connect: connection refused. 

### ISSUE THREAD

**Issue by m00nyONE** [hetznercloud/hcloud-cloud-controller-manager#82]
There is an issue when deploying hcloud-controller with network. Everytime when i try to access a pod or when it should do some kind of callback it always gets lost.
This has to do with the routes set by the virtual network.

```
kubectl node-shell k8s.master.01 | setclip
If you don't see a command prompt, try pressing enter.
Error attaching, falling back to logs: error dialing backend: dial tcp 10.0.0.3:10250: connect: connection refused
Error from server: Get https://10.0.0.3:10250/containerLogs/default/nsenter-nkry4x/nsenter: dial tcp 10.0.0.3:10250: connect: connection refused
```
This happends when i try to SSH into a node.

Same problem with a gitlab kubernetes runner:
```
ERROR: Job failed (system failure): prepare environment: error dialing backend: dial tcp 10.0.0.5:10250: connect: connection refused. 
```
My CNI should be setup correctly. I use flannel on 10.244.0.0/16 for the pods an 10.245.0.0 for the services.

My Pods can only interact with other pods but not outside of the network. the only way to get any kind of connection is via loadbalancer.

**Comment by LKaemmerling** [comment]
Are the routes correctly visible within the Hetzner Cloud Console? If i remember correctly flannel does not support our networks, that's the reason why our docs are with Cilium: https://github.com/hetznercloud/hcloud-cloud-controller-manager/blob/master/docs/deploy_with_networks.md

**Comment by m00nyONE** [comment]
Is there a compatibility list for the CNIs? 
I don't want to use Cilium because it simply does not work on my setup.
Is it because of eBPF?
Is Calico supported?

**Comment by m00nyONE** [comment]
another way to fix this issue is to deploy hcloud without network and then everything works except of the loadBalancers.
They simply fail every healthcheck with the public IP. Internal works but its a hassle to get there.

the easiest fix would be if we where allowed to place an annotation to the loadBalancer Service with the name of the network.

instead of 
```
   load-balancer.hetzner.cloud/use-private-ip: "true"
```
it should be possible to say:
```
   load-balancer.hetzner.cloud/use-private-ip: "vnet0"
```
when vnet0 is the name of the network your nodes are in

**Comment by m00nyONE** [comment]
same problem with cilium 

´´´
kubectl node-shell k8s.master.01
Error attaching, falling back to logs: error dialing backend: dial tcp 10.0.0.3:10250: connect: connection refused
Error from server: Get https://10.0.0.3:10250/containerLogs/default/nsenter-js3a9r/nsenter: dial tcp 10.0.0.3:10250: connect: connection refused
´´´

**Comment by LKaemmerling** [comment]
Could you give me some more information about your setup? Maybe with a server name or ID? It looks like the servers don't route the traffic correctly.

A direct compatibility list is not provided, as we just "fill" the k8s API with functionality. Everything that works directly with the k8s cloud controller API should work.

**Comment by m00nyONE** [comment]
If fixed the issue by deploying a new cluster with kubeadm from scratch.
It seems to be an issue with kubespray. Something just does not match the criteria
