### ISSUE TITLE
Adding existing loadbalancer to cloud-controller-manager

### ISSUE THREAD

**Issue by batistein** [hetznercloud/hcloud-cloud-controller-manager#86]
We have the use case that we create a load balancer using the [cluster-api-provider-hcloud,](https://github.com/cluster-api-provider-hcloud/cluster-api-provider-hcloud) but this is shown as pending. We would now like to register this load balancer with the hcloud-cloud-controller-manager, so that the external IP address is no longer shown as Pending.

**Comment by LKaemmerling** [comment]
This is possible by using the `load-balancer.hetzner.cloud/name` annotation.

**Comment by batistein** [comment]
We use the go-client of Hcloud and the following function to create the load balancer https://pkg.go.dev/github.com/hetznercloud/hcloud-go@v1.22.0/hcloud?tab=doc#LoadBalancerClient.Create.
I think it's not possible to set annotations in this way. How should we do this instead?

**Comment by nazarkulyk** [comment]
Get name from:
```bash
hcloud load-balancer describe <id>
```

Check "Name:"

```yaml
metadata:
 annotations:
    load-balancer.hetzner.cloud/name: <Name>
```

works for me

**Comment by batistein** [comment]
Thank you for your responses! We followed your advice and it actually triggered the HCloud Cloud Controller Manager. However, the result was not what we expected, as all the targets and the network we configured were deleted.
This is why we now just added "externalIPs: - ip" in the service's yaml, so that the external IP is no longer on pending, which is enough for our purposes.
