### ISSUE TITLE
Question: Is it possible to use hetzner load balancer as a default for services?

### ISSUE THREAD

**Issue by cebor** [hetznercloud/hcloud-cloud-controller-manager#88]
Is it possible to use the hetzner lb as a default for all services requesting a lb, without adding any annotations and setting defaults for these?

**Comment by LKaemmerling** [comment]
This is not possible as of the spec from k8s. We don't control the when a LB should created, K8s tell basically the CCM that it should create a Load Balancer when a Service Type Loadbalancer is created/updated.
