### ISSUE TITLE
Support Hetzner hybrid cloud setups

### ISSUE THREAD

**Issue by thetechnick** [hetznercloud/hcloud-cloud-controller-manager#9]
When creating a kubernetes cluster including cloud and bare metal Hetzner servers the hcloud-cloud-controller-manager deletes the bare metal nodes, because they are not found in the Hetzner Cloud.
(See #7)

**Comment by pcallewaert** [comment]
We needed this also, and adjusted the controller to support hcloud and hetzner robot servers:
https://github.com/Be-MobileNV/hcloud-cloud-controller-manager

It's a pretty big chance, so no idea if we push this for a PR if it will get approved. It is a bit out of the scope of this project (hetzner cloud <-> hetzner robot).

**Comment by invidian** [comment]
Maybe initially some annotations could be used to skip the server from removing?

**Comment by identw** [comment]
Try run kubelet on dedicated servers without `--cloud-provider=external`.

**Comment by Bessonov** [comment]
Activity!

**Comment by niklaskorz** [comment]
Is this still considered for implementation? @thetechnick @LKaemmerling

**Comment by LKaemmerling** [comment]
We currently don’t plan to implement this.

**Comment by bradleyhession1** [comment]
Bump this is a nice feature to have for hetzner clients
