### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by micw** [hetznercloud/hcloud-cloud-controller-manager#90]
Hello,

I tried to get the manager running with rancher. So I created a new cluster with "cloud provider = external", manually added one node which then is waiting for the cloud provider to be initialized (`node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule`).

Then I deployed the controller manager. It tries to initialize the node which fails:
```
I0925 11:13:21.847168       1 node_controller.go:325] Initializing node cloud-test-1 with cloud provider
I0925 11:13:21.925767       1 shared_informer.go:230] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::requestheader-client-ca-file
I0925 11:13:21.927165       1 shared_informer.go:230] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0925 11:13:21.936303       1 shared_informer.go:230] Caches are synced for service
E0925 11:13:21.948850       1 node_controller.go:370] failed to initialize node cloud-test-1 at cloudprovider: failed to get instance ID from cloud provider: hcloud/instances.InstanceID: instance not found
I0925 11:13:38.340260       1 node_controller.go:325] Initializing node cloud-test-1 with cloud provider
E0925 11:13:38.441853       1 node_controller.go:370] failed to initialize node cloud-test-1 at cloudprovider: failed to get instance ID from cloud provider: hcloud/instances.InstanceID: instance not found
```
When I manually add the provderId (`kubectl edit node cloud-test-1`), I get one step further:

```
I0925 11:18:38.621871       1 node_controller.go:325] Initializing node cloud-test-1 with cloud provider
E0925 11:18:38.820129       1 node_controller.go:370] failed to initialize node cloud-test-1 at cloudprovider: failed to find kubelet node IP from cloud provider
```
How can I get it to work?

PS: When I create a cluster with "cloud provider = none" instead and add the instance ID, I can get load balancers to work. But I guess that's not a valid setup.

**Comment by LKaemmerling** [comment]
It looks like the API Token you used is not within the same project as the instances are, so the CCM can not find the instance to the given instance ID.

**Comment by micw** [comment]
Node names matches the name in the cloud console. The API token is in the correct project  (I have only one token and this one also works flawlessly for storage and also for node creation with the node driver).

**Comment by LKaemmerling** [comment]
Mmh, the error can only be triggered if the names of the nodes do not match the names in the cloud console. Can you give me a node ID or a project ID? I can then look a bit deeper.

Could you show me a `kubectl describe node/<one-node-name>`? (Keep in mind to remove sensible information).

**Comment by micw** [comment]
Hello,

you are right, there was indeed a mismatch between the cluster node name and the console name (a missing dash). Now I'm one step further.

Io make it reproducible, I have created a new (single-node) cluster:
- manually created a new node, named it hcloud-test-1, added 1 private network
- manually created a new cluster in rancher
   - type custom
   - cloud provider "external"
   - in yaml I added `canal_network_provider: iface: ens10` to make the cluster communicate over the internal network
- added the node to the cluster with roles etcd+control plane+worker and internal IP 10.0.0.5
- rancher provisions the node as hcloud-test-1
- the node has taint "node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule"
- applied the my hcloud-secret.yaml and the cloud-controller-manager-v1.7.0.yaml

I'm now getting the next error:
> failed to initialize node hcloud-test-1 at cloudprovider: failed to find kubelet node IP from cloud provider

**Comment by micw** [comment]
Still open
