### ISSUE TITLE
Shared loadbalancer?

### ISSUE THREAD

**Issue by micw** [hetznercloud/hcloud-cloud-controller-manager#91]
Hello,

in my test, for each service of type "loadbalancer" a new LB is created. Is there an option to use one LB for multiple services?

**Comment by LKaemmerling** [comment]
Based on the k8s spec a k8s service should always belong to a dedicated Load Balancer. One thing you can do is use multiple ports one service and route the service to an ingress (like nginx) and let nginx do the additional routing.

If you want to use an existing LB you can use the `load-balancer.hetzner.cloud/name` or `load-balancer.hetzner.cloud/id` Annotation, but please note that the CCM tries to achieve the state described in the k8s service configuration, so it will delete all services/targets that it does not know about.

Feel free to ask questions or reopen if you have a problem.

**Comment by micw** [comment]
Thank you!
