### ISSUE TITLE
External Hcloud LB puts unhealthy all nodes after scaling

### ISSUE THREAD

**Issue by Ghyron** [hetznercloud/hcloud-cloud-controller-manager#93]
Hello :D

**FOA**: This Issue could be potentially related with this ISSUE https://github.com/hetznercloud/hcloud-cloud-controller-manager/issues/87

I'm reaching strange behavior using hcloud-cloud-controller-manager (with Network Support approach) and Hetzner LoadBalancers service, after deploy a testing Nginx on cluster Load Balancer marks the service as Healthy of one of the nodes, all seems right and every request to LB arrive to Nginx normally, but at the moment that i perform an action that modifies the deployment for example re-scale to two replicas for some seconds LB puts on Healthy the two nodes (I'm still reaching nginx) but with the first healthcheck the LB service change the two nodes to unhealthy status and i can't reach Nginx. Sometimes rescaling to one replica I could reach again the service.

Additional info: from inside the cluster I can reach always the Nginx acros 10.8.0.1 (internal lb ip) and also public LN ip.

Useful information:
Cluster deployed with kubespray using cilum as network plugin

`kubectl get nodes -o wide`
```
NAME          STATUS   ROLES    AGE     VERSION   INTERNAL-IP   EXTERNAL-IP       OS-IMAGE             KERNEL-VERSION     CONTAINER-RUNTIME
k8smaster01   Ready    master   2d23h   v1.19.2   10.8.0.80     <hiding eip>   Ubuntu 20.04.1 LTS   5.4.0-48-generic   docker://19.3.13
k8snode01     Ready    <none>   2d23h   v1.19.2   10.8.0.81     <hiding eip>   Ubuntu 20.04.1 LTS   5.4.0-48-generic   docker://19.3.13
k8snode02     Ready    <none>   2d23h   v1.19.2   10.8.0.82     <hiding eip>    Ubuntu 20.04.1 LTS   5.4.0-48-generic   docker://19.3.13
```
`kubectl get pods --all-namespaces -o wide`
```
NAMESPACE     NAME                                               READY   STATUS    RESTARTS   AGE     IP              NODE          NOMINATED NODE   READINESS GATES
default       nginx-hello-world-7f79fc7b8b-dq289                 1/1     Running   0          20h     10.233.66.107   k8snode02     <none>           <none>
kube-system   cilium-ftn9b                                       1/1     Running   1          2d23h   10.8.0.82       k8snode02     <none>           <none>
kube-system   cilium-m86lk                                       1/1     Running   2          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   cilium-operator-6c46767cc5-wvvdj                   1/1     Running   7          2d23h   10.8.0.82       k8snode02     <none>           <none>
kube-system   cilium-tkkhx                                       1/1     Running   1          2d23h   10.8.0.81       k8snode01     <none>           <none>
kube-system   coredns-8677555d68-jp495                           1/1     Running   1          2d23h   10.233.66.195   k8snode02     <none>           <none>
kube-system   coredns-8677555d68-vqqgl                           1/1     Running   1          2d23h   10.233.65.218   k8snode01     <none>           <none>
kube-system   dns-autoscaler-5b7b5c9b6f-nkfxw                    1/1     Running   1          2d23h   10.233.65.76    k8snode01     <none>           <none>
kube-system   hcloud-cloud-controller-manager-5974697849-mr6wr   1/1     Running   2          2d23h   10.8.0.81       k8snode01     <none>           <none>
kube-system   hcloud-csi-controller-0                            5/5     Running   6          2d23h   10.233.65.23    k8snode01     <none>           <none>
kube-system   hcloud-csi-node-78ltg                              3/3     Running   4          2d23h   10.233.65.102   k8snode01     <none>           <none>
kube-system   hcloud-csi-node-wsbmp                              3/3     Running   4          2d23h   10.233.66.74    k8snode02     <none>           <none>
kube-system   hcloud-csi-node-zkm4t                              3/3     Running   6          2d23h   10.233.64.24    k8smaster01   <none>           <none>
kube-system   kube-apiserver-k8smaster01                         1/1     Running   5          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   kube-controller-manager-k8smaster01                1/1     Running   3          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   kube-proxy-fw588                                   1/1     Running   1          2d23h   10.8.0.81       k8snode01     <none>           <none>
kube-system   kube-proxy-gqmzp                                   1/1     Running   1          2d23h   10.8.0.82       k8snode02     <none>           <none>
kube-system   kube-proxy-msf7t                                   1/1     Running   2          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   kube-scheduler-k8smaster01                         1/1     Running   3          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   kubernetes-dashboard-dfb67d98c-2rls8               1/1     Running   7          2d23h   10.233.64.224   k8smaster01   <none>           <none>
kube-system   kubernetes-metrics-scraper-54df648466-664dt        1/1     Running   3          2d23h   10.233.64.30    k8smaster01   <none>           <none>
kube-system   nginx-proxy-k8snode01                              1/1     Running   1          2d23h   10.8.0.81       k8snode01     <none>           <none>
kube-system   nginx-proxy-k8snode02                              1/1     Running   1          2d23h   10.8.0.82       k8snode02     <none>           <none>
kube-system   nodelocaldns-4vbcr                                 1/1     Running   2          2d23h   10.8.0.80       k8smaster01   <none>           <none>
kube-system   nodelocaldns-5zjpc                                 1/1     Running   1          2d23h   10.8.0.82       k8snode02     <none>           <none>
kube-system   nodelocaldns-ltfpn                                 1/1     Running   1          2d23h   10.8.0.81       k8snode01     <none>           <none>
```
`kubectl get services`
```
NAME                TYPE           CLUSTER-IP      EXTERNAL-IP              PORT(S)        AGE
kubernetes          ClusterIP      10.233.0.1      <none>                   443/TCP        2d23h
nginx-hello-world   LoadBalancer   10.233.62.102   10.8.0.1,<hiding eip>   80:30922/TCP   2m31s
```
`kubectl describe services nginx-hello-world`
```
Name:                     nginx-hello-world
Namespace:                default
Labels:                   app=hello-world
Annotations:              load-balancer.hetzner.cloud/location: nbg1
                          load-balancer.hetzner.cloud/name: testk8slb
                          load-balancer.hetzner.cloud/use-private-ip: true
Selector:                 app=hello-world
Type:                     LoadBalancer
IP:                       10.233.62.102
LoadBalancer Ingress:     <hide eip>, 10.8.0.1
Port:                     http  80/TCP
TargetPort:               80/TCP
NodePort:                 http  30922/TCP
Endpoints:                10.233.66.107:80
Session Affinity:         None
External Traffic Policy:  Cluster
Events:
  Type    Reason                Age   From                Message
  ----    ------                ----  ----                -------
  Normal  EnsuringLoadBalancer  24m   service-controller  Ensuring load balancer
  Normal  EnsuredLoadBalancer   24m   service-controller  Ensured load balancer

```
After scaling:
![Screenshot_20200930_201929](https://user-images.githubusercontent.com/1719134/94724291-5b61ad00-035a-11eb-8f97-1acffb535ca9.png)

Sorry if I'm missing something and thank you very much!

**Comment by LKaemmerling** [comment]
Hey @Ghyron,

does the health check turn healthy after the configured time? (~30 sec is default) Is the Node Port (30922) accessible on that machine?

**Comment by LKaemmerling** [comment]
We fixed a small bug within the latest release, could you try this? (v1.8.0)

**Comment by Ghyron** [comment]
Yes, I was just trying v1.8.0 but I'm reaching another problem
```
controller.go:244] error processing service default/nginx-hello-world (will retry): failed to ensure load balancer: hcloud/loadBalancers.EnsureLoadBalancer: hcops/LoadBalancerOps.ReconcileHCLBTargets: use private ip: missing network id
```
There is any new parameter mandatory with `load-balancer.hetzner.cloud/use-private-ip: "true"` ?

Thank you.

**Comment by LKaemmerling** [comment]
Do you use the networks version and use our cloud networks?

**Comment by Ghyron** [comment]
With the rush i forgot use the correct one (cloud networks) sorry.

Unfortunatelly I've the same behavior with `Image:         hetznercloud/hcloud-cloud-controller-manager:v1.8.0`.

By the way I've tested with public ips and I reach the same issue.

**Comment by Ghyron** [comment]
Helo @LKaemmerling.

I did some more investigations and tests and seems working as expected if I configure the service using NodePort and then configure the LB manually, so I would dare to say there is some problem or mismatch with the LB - Service configuration, If I can help providing more information of this behavior I will be happy to help.

Thank you.

**Comment by LKaemmerling** [comment]
Hey @Ghyron,

could you please give me an ID from one of your resources? I can then look if i can see something strange from our side. It should work if you always use the NodePort, as the LB sends the traffic to the nodes.

**Comment by Ghyron** [comment]
Hello @LKaemmerling,

It's a testing env so no problem, currently I reproduced de behavior with 2 replicas and healthchecks are down, you can check it on LB with id #106493, if you need that I take some actions just tell me.

**Comment by LKaemmerling** [comment]
Hey @Ghyron,

what I found so far:
- Both pods are available via the Public Interface and the node port: 30452 (responds with default nginx page)
- The service is configured to with `use_private_ip`= true, so the LB tries to connect to the nodes via 10.8.0.82 and 10.8.0.81, but both are not available to the Health Check which then of course fail. 

From the LB configuration, everything looks fine, so maybe it is a firewall issue on the nodes?

**Comment by Ghyron** [comment]
Hello @LKaemmerling,

Now I downscaled to one replica and LB puts healthcheck to up how can be related to firewall, sorry maybe I'm missing something.

**Comment by LKaemmerling** [comment]
Could you please give me your service definition and your deployment? The Port 30452 is now accessible within the private network but, it still accessible from both public IPs (with the direct port)

**Comment by Ghyron** [comment]
Sure, it's just a simple testing app 

Deployment:
```
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
spec:
  selector:
    matchLabels:
      app: "hello-world"
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        app: "hello-world"
    spec:
      containers:
        - image: "nginx"
          name: "nginx-hello-world"
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
              name: "http"
```
Service:
```
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "nginx-hello-world"
  labels:
    app: "hello-world"
  annotations:
    load-balancer.hetzner.cloud/name: "testk8slb"
    load-balancer.hetzner.cloud/use-private-ip: "true"
    load-balancer.hetzner.cloud/network: "k8services_network"
    load-balancer.hetzner.cloud/location: nbg1
    load-balancer.hetzner.cloud/network-zone: eu-central
spec:
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: "hello-world"
  type: LoadBalancer
```

**Comment by LKaemmerling** [comment]
Hey @Ghyron,

we tried it with your deployment file and can not reproduce the problem. We can easily scale without any problems and the health checks work as expected. One of our SysOps gave me the hint that maybe there is something wrong on your cilium setup?  

Within our testcluster we also use cilium (with the cloud controller manager) and it works as expected. Can you try to connect to the pods from within your cluster (or nodes, like the LB would do)? That's the only thing i can recommend you, on our end everything looks fine and we can't see any issue.

**Comment by Ghyron** [comment]
Hello @LKaemmerling,

First of all thanks for test this, this afternoon I will look deeper on cilium conf.

From inside the cluster I can always curl the service succesfully in any of the cluster IP's public or private with one or two replicas even when healthchecker is down, so thats why I always was suspecting on networking or routing side because pods are deployed on 10.233.0.0/16, What do you mean with `Can you try to connect to the pods from within your cluster (or nodes, like the LB would do)` I can "nc" those ports from every node.

How can check/verify the step 7 on https://github.com/LKaemmerling/hcloud-k8s-test-cases/tree/main/ccm/issues/93

**Comment by Ghyron** [comment]
New findings, I just created the LB manually and works like a charm, must be something related to my Cluster configuration, maybe CCM vs Cilium have something missconfigured.

**Comment by Ghyron** [comment]
Hello @LKaemmerling,

I've managed to get it working I've check (again) package annotation and i found one related to Ingress, in my tests there was no ingress involved for the moment, so adding the following annotation all works like a charm.
`load-balancer.hetzner.cloud/disable-private-ingress: "true"`

Just one thing that you pointed, when I create the service using loadBlancer type, Cilium set the services also on public interfaces there is way to avoid that? I've check this and I'm not sure if this can be done with Cilium which automatically expose service on all the interfaces.

Thank you!
